import { MetricRegistryEntry } from "./analyticsTypes";

export const METRIC_CATALOG: Record<string, MetricRegistryEntry> = {
  active_signals_24h: {
    id: "active_signals_24h",
    name: "Active Signals 24H",
    shortDescription: "Métrica: Active Signals 24H",
    origin: "system",
    allowedAudience: ["results", "admin"],
    level: "base",
    outputType: "number",
    family: "behavior",
    surfaces: ['results_hero','admin_registry'],
    status: "live",
    staticOrTrend: "hybrid",
    visibleByDefault: true,
    requiresGuardrail: true,
    minSample: 50,
    minNEff: 30,
    maxFreshnessHours: 24,
    requiresAnonymityGuardrail: true,
    exportable: true,
    uiVariant: "table_column",
    defaultSlot: "hero",
    defaultSortOrder: 0,
    isWiredToReadModel: true,
    isWiredToUI: true,
  },
  active_entities_24h: {
    id: "active_entities_24h",
    name: "Active Entities 24H",
    shortDescription: "Métrica: Active Entities 24H",
    origin: "system",
    allowedAudience: ["results", "admin"],
    level: "base",
    outputType: "number",
    family: "rigor",
    surfaces: ['admin_registry'],
    status: "pending_instrumentation",
    staticOrTrend: "hybrid",
    visibleByDefault: false,
    requiresGuardrail: true,
    minSample: 50,
    minNEff: 30,
    maxFreshnessHours: 24,
    requiresAnonymityGuardrail: true,
    exportable: true,
    uiVariant: "table_column",
    defaultSlot: "details",
    defaultSortOrder: 0,
    isWiredToReadModel: false,
    isWiredToUI: false,
  },
  active_categories_24h: {
    id: "active_categories_24h",
    name: "Active Categories 24H",
    shortDescription: "Métrica: Active Categories 24H",
    origin: "system",
    allowedAudience: ["results", "admin"],
    level: "base",
    outputType: "number",
    family: "rigor",
    surfaces: ['admin_registry'],
    status: "pending_instrumentation",
    staticOrTrend: "hybrid",
    visibleByDefault: false,
    requiresGuardrail: true,
    minSample: 50,
    minNEff: 30,
    maxFreshnessHours: 24,
    requiresAnonymityGuardrail: true,
    exportable: true,
    uiVariant: "table_column",
    defaultSlot: "details",
    defaultSortOrder: 0,
    isWiredToReadModel: false,
    isWiredToUI: false,
  },
  freshness_hours: {
    id: "freshness_hours",
    name: "Freshness Hours",
    shortDescription: "Métrica: Freshness Hours",
    origin: "system",
    allowedAudience: ["results", "admin"],
    level: "base",
    outputType: "number",
    family: "rigor",
    surfaces: ['results_hero','admin_registry'],
    status: "live",
    staticOrTrend: "hybrid",
    visibleByDefault: true,
    requiresGuardrail: true,
    minSample: 50,
    minNEff: 30,
    maxFreshnessHours: 24,
    requiresAnonymityGuardrail: true,
    exportable: true,
    uiVariant: "table_column",
    defaultSlot: "hero",
    defaultSortOrder: 0,
    isWiredToReadModel: true,
    isWiredToUI: true,
  },
  community_activity_label: {
    id: "community_activity_label",
    name: "Community Activity Label",
    shortDescription: "Métrica: Community Activity Label",
    origin: "system",
    allowedAudience: ["results", "admin"],
    level: "base",
    outputType: "label",
    family: "rigor",
    surfaces: ['results_hero','results_pulse','admin_registry'],
    status: "live",
    staticOrTrend: "hybrid",
    visibleByDefault: true,
    requiresGuardrail: true,
    minSample: 50,
    minNEff: 30,
    maxFreshnessHours: 24,
    requiresAnonymityGuardrail: true,
    exportable: true,
    uiVariant: "editorial_chip",
    defaultSlot: "hero",
    defaultSortOrder: 0,
    isWiredToReadModel: true,
    isWiredToUI: true,
  },
  preference_share_leader: {
    id: "preference_share_leader",
    name: "Preference Share Leader",
    shortDescription: "Métrica: Preference Share Leader",
    origin: "versus",
    allowedAudience: ["results", "admin"],
    level: "base",
    outputType: "interval",
    family: "market",
    surfaces: ['results_versus','admin_registry'],
    status: "live",
    staticOrTrend: "hybrid",
    visibleByDefault: true,
    requiresGuardrail: true,
    minSample: 50,
    minNEff: 30,
    maxFreshnessHours: 24,
    requiresAnonymityGuardrail: true,
    exportable: true,
    uiVariant: "kpi_card",
    defaultSlot: "hero",
    defaultSortOrder: 0,
    isWiredToReadModel: true,
    isWiredToUI: true,
  },
  leader_entity_name: {
    id: "leader_entity_name",
    name: "Leader Entity Name",
    shortDescription: "Métrica: Leader Entity Name",
    origin: "versus",
    allowedAudience: ["results", "admin"],
    level: "base",
    outputType: "label",
    family: "market",
    surfaces: ['results_versus','admin_registry'],
    status: "live",
    staticOrTrend: "hybrid",
    visibleByDefault: true,
    requiresGuardrail: true,
    minSample: 50,
    minNEff: 30,
    maxFreshnessHours: 24,
    requiresAnonymityGuardrail: true,
    exportable: true,
    uiVariant: "table_column",
    defaultSlot: "hero",
    defaultSortOrder: 0,
    isWiredToReadModel: true,
    isWiredToUI: true,
  },
  leader_margin_vs_second: {
    id: "leader_margin_vs_second",
    name: "Leader Margin Vs Second",
    shortDescription: "Métrica: Leader Margin Vs Second",
    origin: "versus",
    allowedAudience: ["results", "admin"],
    level: "base",
    outputType: "interval",
    family: "market",
    surfaces: ['results_versus','admin_registry'],
    status: "live",
    staticOrTrend: "hybrid",
    visibleByDefault: true,
    requiresGuardrail: true,
    minSample: 50,
    minNEff: 30,
    maxFreshnessHours: 24,
    requiresAnonymityGuardrail: true,
    exportable: true,
    uiVariant: "table_column",
    defaultSlot: "hero",
    defaultSortOrder: 0,
    isWiredToReadModel: true,
    isWiredToUI: true,
  },
  most_contested_category: {
    id: "most_contested_category",
    name: "Most Contested Category",
    shortDescription: "Métrica: Most Contested Category",
    origin: "system",
    allowedAudience: ["results", "admin"],
    level: "base",
    outputType: "number",
    family: "rigor",
    surfaces: ['results_versus','admin_registry'],
    status: "live",
    staticOrTrend: "hybrid",
    visibleByDefault: true,
    requiresGuardrail: true,
    minSample: 50,
    minNEff: 30,
    maxFreshnessHours: 24,
    requiresAnonymityGuardrail: true,
    exportable: true,
    uiVariant: "table_column",
    defaultSlot: "hero",
    defaultSortOrder: 0,
    isWiredToReadModel: true,
    isWiredToUI: true,
  },
  fastest_riser_entity: {
    id: "fastest_riser_entity",
    name: "Fastest Riser Entity",
    shortDescription: "Métrica: Fastest Riser Entity",
    origin: "system",
    allowedAudience: ["results", "admin"],
    level: "base",
    outputType: "entity_ref",
    family: "rigor",
    surfaces: ['results_pulse','admin_registry'],
    status: "live",
    staticOrTrend: "hybrid",
    visibleByDefault: true,
    requiresGuardrail: true,
    minSample: 50,
    minNEff: 30,
    maxFreshnessHours: 24,
    requiresAnonymityGuardrail: true,
    exportable: true,
    uiVariant: "table_column",
    defaultSlot: "hero",
    defaultSortOrder: 0,
    isWiredToReadModel: true,
    isWiredToUI: true,
  },
  fastest_faller_entity: {
    id: "fastest_faller_entity",
    name: "Fastest Faller Entity",
    shortDescription: "Métrica: Fastest Faller Entity",
    origin: "system",
    allowedAudience: ["results", "admin"],
    level: "base",
    outputType: "entity_ref",
    family: "rigor",
    surfaces: ['results_pulse','admin_registry'],
    status: "live",
    staticOrTrend: "hybrid",
    visibleByDefault: true,
    requiresGuardrail: true,
    minSample: 50,
    minNEff: 30,
    maxFreshnessHours: 24,
    requiresAnonymityGuardrail: true,
    exportable: true,
    uiVariant: "table_column",
    defaultSlot: "hero",
    defaultSortOrder: 0,
    isWiredToReadModel: true,
    isWiredToUI: true,
  },
  dominant_choice_label: {
    id: "dominant_choice_label",
    name: "Dominant Choice Label",
    shortDescription: "Métrica: Dominant Choice Label",
    origin: "system",
    allowedAudience: ["results", "admin"],
    level: "base",
    outputType: "label",
    family: "rigor",
    surfaces: ['admin_registry'],
    status: "pending_instrumentation",
    staticOrTrend: "hybrid",
    visibleByDefault: false,
    requiresGuardrail: true,
    minSample: 50,
    minNEff: 30,
    maxFreshnessHours: 24,
    requiresAnonymityGuardrail: true,
    exportable: true,
    uiVariant: "editorial_chip",
    defaultSlot: "details",
    defaultSortOrder: 0,
    isWiredToReadModel: true,
    isWiredToUI: true,
  },
  market_tension_index: {
    id: "market_tension_index",
    name: "Market Tension Index",
    shortDescription: "Métrica: Market Tension Index",
    origin: "system",
    allowedAudience: ["results", "admin"],
    level: "base",
    outputType: "score",
    family: "market",
    surfaces: ['results_hero','admin_registry'],
    status: "pending_instrumentation",
    staticOrTrend: "hybrid",
    visibleByDefault: false,
    requiresGuardrail: true,
    minSample: 50,
    minNEff: 30,
    maxFreshnessHours: 24,
    requiresAnonymityGuardrail: true,
    exportable: true,
    uiVariant: "table_column",
    defaultSlot: "hero",
    defaultSortOrder: 0,
    isWiredToReadModel: false,
    isWiredToUI: false,
  },
  consensus_polarization_label: {
    id: "consensus_polarization_label",
    name: "Consensus Polarization Label",
    shortDescription: "Métrica: Consensus Polarization Label",
    origin: "system",
    allowedAudience: ["results", "admin"],
    level: "base",
    outputType: "label",
    family: "rigor",
    surfaces: ['admin_registry'],
    status: "pending_instrumentation",
    staticOrTrend: "hybrid",
    visibleByDefault: false,
    requiresGuardrail: true,
    minSample: 50,
    minNEff: 30,
    maxFreshnessHours: 24,
    requiresAnonymityGuardrail: true,
    exportable: true,
    uiVariant: "editorial_chip",
    defaultSlot: "details",
    defaultSortOrder: 0,
    isWiredToReadModel: false,
    isWiredToUI: false,
  },
  fragmentation_label: {
    id: "fragmentation_label",
    name: "Fragmentation Label",
    shortDescription: "Métrica: Fragmentation Label",
    origin: "system",
    allowedAudience: ["results", "intelligence", "admin"],
    level: "base",
    outputType: "label",
    family: "rigor",
    surfaces: ['results_pulse','b2b_overview_top','admin_registry'],
    status: "live",
    staticOrTrend: "hybrid",
    visibleByDefault: true,
    requiresGuardrail: true,
    minSample: 50,
    minNEff: 30,
    maxFreshnessHours: 24,
    requiresAnonymityGuardrail: true,
    exportable: true,
    uiVariant: "editorial_chip",
    defaultSlot: "hero",
    defaultSortOrder: 0,
    isWiredToReadModel: true,
    isWiredToUI: true,
  },
  category_volatility_label: {
    id: "category_volatility_label",
    name: "Category Volatility Label",
    shortDescription: "Métrica: Category Volatility Label",
    origin: "system",
    allowedAudience: ["results", "admin"],
    level: "base",
    outputType: "label",
    family: "rigor",
    surfaces: ['admin_registry'],
    status: "pending_instrumentation",
    staticOrTrend: "hybrid",
    visibleByDefault: false,
    requiresGuardrail: true,
    minSample: 50,
    minNEff: 30,
    maxFreshnessHours: 24,
    requiresAnonymityGuardrail: true,
    exportable: true,
    uiVariant: "editorial_chip",
    defaultSlot: "details",
    defaultSortOrder: 0,
    isWiredToReadModel: false,
    isWiredToUI: false,
  },
  current_champion_entity: {
    id: "current_champion_entity",
    name: "Current Champion Entity",
    shortDescription: "Métrica: Current Champion Entity",
    origin: "tournament",
    allowedAudience: ["results", "admin"],
    level: "base",
    outputType: "entity_ref",
    family: "rigor",
    surfaces: ['results_tournament','admin_registry'],
    status: "pending_instrumentation",
    staticOrTrend: "hybrid",
    visibleByDefault: false,
    requiresGuardrail: true,
    minSample: 50,
    minNEff: 30,
    maxFreshnessHours: 24,
    requiresAnonymityGuardrail: true,
    exportable: true,
    uiVariant: "table_column",
    defaultSlot: "details",
    defaultSortOrder: 0,
    isWiredToReadModel: true,
    isWiredToUI: true,
  },
  champion_stability_label: {
    id: "champion_stability_label",
    name: "Champion Stability Label",
    shortDescription: "Métrica: Champion Stability Label",
    origin: "tournament",
    allowedAudience: ["results", "admin"],
    level: "base",
    outputType: "label",
    family: "rigor",
    surfaces: ['results_tournament','admin_registry'],
    status: "live",
    staticOrTrend: "hybrid",
    visibleByDefault: false,
    requiresGuardrail: true,
    minSample: 50,
    minNEff: 30,
    maxFreshnessHours: 24,
    requiresAnonymityGuardrail: true,
    exportable: true,
    uiVariant: "editorial_chip",
    defaultSlot: "details",
    defaultSortOrder: 0,
    isWiredToReadModel: true,
    isWiredToUI: true,
  },
  upset_rate_label: {
    id: "upset_rate_label",
    name: "Upset Rate Label",
    shortDescription: "Métrica: Upset Rate Label",
    origin: "system",
    allowedAudience: ["results", "admin"],
    level: "base",
    outputType: "label",
    family: "behavior",
    surfaces: ['results_tournament','admin_registry'],
    status: "pending_instrumentation",
    staticOrTrend: "hybrid",
    visibleByDefault: false,
    requiresGuardrail: true,
    minSample: 50,
    minNEff: 30,
    maxFreshnessHours: 24,
    requiresAnonymityGuardrail: true,
    exportable: true,
    uiVariant: "editorial_chip",
    defaultSlot: "details",
    defaultSortOrder: 0,
    isWiredToReadModel: true,
    isWiredToUI: true,
  },
  most_difficult_path_entity: {
    id: "most_difficult_path_entity",
    name: "Most Difficult Path Entity",
    shortDescription: "Métrica: Most Difficult Path Entity",
    origin: "system",
    allowedAudience: ["results", "admin"],
    level: "base",
    outputType: "entity_ref",
    family: "rigor",
    surfaces: ['results_tournament','admin_registry'],
    status: "pending_instrumentation",
    staticOrTrend: "hybrid",
    visibleByDefault: false,
    requiresGuardrail: true,
    minSample: 50,
    minNEff: 30,
    maxFreshnessHours: 24,
    requiresAnonymityGuardrail: true,
    exportable: true,
    uiVariant: "table_column",
    defaultSlot: "details",
    defaultSortOrder: 0,
    isWiredToReadModel: true,
    isWiredToUI: true,
  },
  top_strength_attribute: {
    id: "top_strength_attribute",
    name: "Top Strength Attribute",
    shortDescription: "Métrica: Top Strength Attribute",
    origin: "depth",
    allowedAudience: ["results", "admin"],
    level: "base",
    outputType: "number",
    family: "depth",
    surfaces: ['results_depth','admin_registry'],
    status: "live",
    staticOrTrend: "hybrid",
    visibleByDefault: true,
    requiresGuardrail: true,
    minSample: 50,
    minNEff: 30,
    maxFreshnessHours: 24,
    requiresAnonymityGuardrail: true,
    exportable: true,
    uiVariant: "table_column",
    defaultSlot: "hero",
    defaultSortOrder: 0,
    isWiredToReadModel: true,
    isWiredToUI: true,
  },
  top_pain_attribute: {
    id: "top_pain_attribute",
    name: "Top Pain Attribute",
    shortDescription: "Métrica: Top Pain Attribute",
    origin: "depth",
    allowedAudience: ["results", "admin"],
    level: "base",
    outputType: "number",
    family: "depth",
    surfaces: ['results_depth','admin_registry'],
    status: "live",
    staticOrTrend: "hybrid",
    visibleByDefault: true,
    requiresGuardrail: true,
    minSample: 50,
    minNEff: 30,
    maxFreshnessHours: 24,
    requiresAnonymityGuardrail: true,
    exportable: true,
    uiVariant: "table_column",
    defaultSlot: "hero",
    defaultSortOrder: 0,
    isWiredToReadModel: true,
    isWiredToUI: true,
  },
  best_rated_entity: {
    id: "best_rated_entity",
    name: "Best Rated Entity",
    shortDescription: "Métrica: Best Rated Entity",
    origin: "system",
    allowedAudience: ["results", "admin"],
    level: "base",
    outputType: "entity_ref",
    family: "behavior",
    surfaces: ['admin_registry'],
    status: "pending_instrumentation",
    staticOrTrend: "hybrid",
    visibleByDefault: false,
    requiresGuardrail: true,
    minSample: 50,
    minNEff: 30,
    maxFreshnessHours: 24,
    requiresAnonymityGuardrail: true,
    exportable: true,
    uiVariant: "table_column",
    defaultSlot: "details",
    defaultSortOrder: 0,
    isWiredToReadModel: true,
    isWiredToUI: true,
  },
  worst_rated_entity: {
    id: "worst_rated_entity",
    name: "Worst Rated Entity",
    shortDescription: "Métrica: Worst Rated Entity",
    origin: "system",
    allowedAudience: ["results", "admin"],
    level: "base",
    outputType: "entity_ref",
    family: "behavior",
    surfaces: ['admin_registry'],
    status: "pending_instrumentation",
    staticOrTrend: "hybrid",
    visibleByDefault: false,
    requiresGuardrail: true,
    minSample: 50,
    minNEff: 30,
    maxFreshnessHours: 24,
    requiresAnonymityGuardrail: true,
    exportable: true,
    uiVariant: "table_column",
    defaultSlot: "details",
    defaultSortOrder: 0,
    isWiredToReadModel: true,
    isWiredToUI: true,
  },
  nps_leader_entity: {
    id: "nps_leader_entity",
    name: "Líder NPS",
    shortDescription: "Métrica: Líder NPS",
    origin: "depth",
    allowedAudience: ["results", "admin"],
    level: "base",
    outputType: "entity_ref",
    family: "market",
    surfaces: ['results_depth','admin_registry'],
    status: "live",
    staticOrTrend: "hybrid",
    visibleByDefault: true,
    requiresGuardrail: true,
    minSample: 50,
    minNEff: 30,
    maxFreshnessHours: 24,
    requiresAnonymityGuardrail: true,
    exportable: true,
    uiVariant: "table_column",
    defaultSlot: "hero",
    defaultSortOrder: 0,
    isWiredToReadModel: true,
    isWiredToUI: true,
  },
  quality_perception_label: {
    id: "quality_perception_label",
    name: "Quality Perception Label",
    shortDescription: "Métrica: Quality Perception Label",
    origin: "system",
    allowedAudience: ["results", "admin"],
    level: "base",
    outputType: "label",
    family: "depth",
    surfaces: ['admin_registry'],
    status: "pending_instrumentation",
    staticOrTrend: "hybrid",
    visibleByDefault: false,
    requiresGuardrail: true,
    minSample: 50,
    minNEff: 30,
    maxFreshnessHours: 24,
    requiresAnonymityGuardrail: true,
    exportable: true,
    uiVariant: "editorial_chip",
    defaultSlot: "details",
    defaultSortOrder: 0,
    isWiredToReadModel: true,
    isWiredToUI: true,
  },
  hot_topic_title: {
    id: "hot_topic_title",
    name: "Hot Topic Title",
    shortDescription: "Métrica: Hot Topic Title",
    origin: "news",
    allowedAudience: ["results", "admin"],
    level: "base",
    outputType: "label",
    family: "actualidad",
    surfaces: ['results_news','admin_registry'],
    status: "live",
    staticOrTrend: "hybrid",
    visibleByDefault: true,
    requiresGuardrail: true,
    minSample: 50,
    minNEff: 30,
    maxFreshnessHours: 24,
    requiresAnonymityGuardrail: true,
    exportable: true,
    uiVariant: "table_column",
    defaultSlot: "hero",
    defaultSortOrder: 0,
    isWiredToReadModel: true,
    isWiredToUI: true,
  },
  hot_topic_heat_index: {
    id: "hot_topic_heat_index",
    name: "Hot Topic Heat Index",
    shortDescription: "Métrica: Hot Topic Heat Index",
    origin: "news",
    allowedAudience: ["results", "admin"],
    level: "base",
    outputType: "score",
    family: "actualidad",
    surfaces: ['results_news','admin_registry'],
    status: "live",
    staticOrTrend: "hybrid",
    visibleByDefault: true,
    requiresGuardrail: true,
    minSample: 50,
    minNEff: 30,
    maxFreshnessHours: 24,
    requiresAnonymityGuardrail: true,
    exportable: true,
    uiVariant: "table_column",
    defaultSlot: "hero",
    defaultSortOrder: 0,
    isWiredToReadModel: true,
    isWiredToUI: true,
  },
  hot_topic_resonance_label: {
    id: "hot_topic_resonance_label",
    name: "Hot Topic Resonance Label",
    shortDescription: "Métrica: Hot Topic Resonance Label",
    origin: "news",
    allowedAudience: ["results", "admin"],
    level: "base",
    outputType: "label",
    family: "actualidad",
    surfaces: ['admin_registry'],
    status: "pending_instrumentation",
    staticOrTrend: "hybrid",
    visibleByDefault: false,
    requiresGuardrail: true,
    minSample: 50,
    minNEff: 30,
    maxFreshnessHours: 24,
    requiresAnonymityGuardrail: true,
    exportable: true,
    uiVariant: "editorial_chip",
    defaultSlot: "details",
    defaultSortOrder: 0,
    isWiredToReadModel: false,
    isWiredToUI: false,
  },
  hot_topic_polarization_label: {
    id: "hot_topic_polarization_label",
    name: "Hot Topic Polarization Label",
    shortDescription: "Métrica: Hot Topic Polarization Label",
    origin: "news",
    allowedAudience: ["results", "admin"],
    level: "base",
    outputType: "label",
    family: "actualidad",
    surfaces: ['results_news','admin_registry'],
    status: "live",
    staticOrTrend: "hybrid",
    visibleByDefault: true,
    requiresGuardrail: true,
    minSample: 50,
    minNEff: 30,
    maxFreshnessHours: 24,
    requiresAnonymityGuardrail: true,
    exportable: true,
    uiVariant: "editorial_chip",
    defaultSlot: "hero",
    defaultSortOrder: 0,
    isWiredToReadModel: true,
    isWiredToUI: true,
  },
  fastest_reaction_topic: {
    id: "fastest_reaction_topic",
    name: "Fastest Reaction Topic",
    shortDescription: "Métrica: Fastest Reaction Topic",
    origin: "news",
    allowedAudience: ["results", "admin"],
    level: "base",
    outputType: "number",
    family: "actualidad",
    surfaces: ['results_news','admin_registry'],
    status: "pending_instrumentation",
    staticOrTrend: "hybrid",
    visibleByDefault: false,
    requiresGuardrail: true,
    minSample: 50,
    minNEff: 30,
    maxFreshnessHours: 24,
    requiresAnonymityGuardrail: true,
    exportable: true,
    uiVariant: "table_column",
    defaultSlot: "details",
    defaultSortOrder: 0,
    isWiredToReadModel: true,
    isWiredToUI: true,
  },
  topic_with_most_consensus: {
    id: "topic_with_most_consensus",
    name: "Topic With Most Consensus",
    shortDescription: "Métrica: Topic With Most Consensus",
    origin: "news",
    allowedAudience: ["results", "admin"],
    level: "base",
    outputType: "number",
    family: "actualidad",
    surfaces: ['results_news','admin_registry'],
    status: "pending_instrumentation",
    staticOrTrend: "hybrid",
    visibleByDefault: false,
    requiresGuardrail: true,
    minSample: 50,
    minNEff: 30,
    maxFreshnessHours: 24,
    requiresAnonymityGuardrail: true,
    exportable: true,
    uiVariant: "table_column",
    defaultSlot: "details",
    defaultSortOrder: 0,
    isWiredToReadModel: true,
    isWiredToUI: true,
  },
  topic_with_most_division: {
    id: "topic_with_most_division",
    name: "Topic With Most Division",
    shortDescription: "Métrica: Topic With Most Division",
    origin: "news",
    allowedAudience: ["results", "admin"],
    level: "base",
    outputType: "number",
    family: "actualidad",
    surfaces: ['results_news','admin_registry'],
    status: "pending_instrumentation",
    staticOrTrend: "hybrid",
    visibleByDefault: false,
    requiresGuardrail: true,
    minSample: 50,
    minNEff: 30,
    maxFreshnessHours: 24,
    requiresAnonymityGuardrail: true,
    exportable: true,
    uiVariant: "table_column",
    defaultSlot: "details",
    defaultSortOrder: 0,
    isWiredToReadModel: true,
    isWiredToUI: true,
  },
  generation_gap_label: {
    id: "generation_gap_label",
    name: "Generation Gap Label",
    shortDescription: "Métrica: Generation Gap Label",
    origin: "system",
    allowedAudience: ["results", "admin"],
    level: "base",
    outputType: "label",
    family: "segments",
    surfaces: ['results_pulse','results_footer','admin_registry'],
    status: "live",
    staticOrTrend: "hybrid",
    visibleByDefault: true,
    requiresGuardrail: true,
    minSample: 50,
    minNEff: 30,
    maxFreshnessHours: 24,
    requiresAnonymityGuardrail: true,
    exportable: true,
    uiVariant: "editorial_chip",
    defaultSlot: "hero",
    defaultSortOrder: 0,
    isWiredToReadModel: true,
    isWiredToUI: true,
  },
  territory_gap_label: {
    id: "territory_gap_label",
    name: "Territory Gap Label",
    shortDescription: "Métrica: Territory Gap Label",
    origin: "system",
    allowedAudience: ["results", "admin"],
    level: "base",
    outputType: "label",
    family: "segments",
    surfaces: ['results_footer','admin_registry'],
    status: "live",
    staticOrTrend: "hybrid",
    visibleByDefault: true,
    requiresGuardrail: true,
    minSample: 50,
    minNEff: 30,
    maxFreshnessHours: 24,
    requiresAnonymityGuardrail: true,
    exportable: true,
    uiVariant: "editorial_chip",
    defaultSlot: "hero",
    defaultSortOrder: 0,
    isWiredToReadModel: true,
    isWiredToUI: true,
  },
  segment_with_highest_divergence: {
    id: "segment_with_highest_divergence",
    name: "Segment With Highest Divergence",
    shortDescription: "Métrica: Segment With Highest Divergence",
    origin: "system",
    allowedAudience: ["results", "admin"],
    level: "base",
    outputType: "number",
    family: "segments",
    surfaces: ['admin_registry'],
    status: "pending_instrumentation",
    staticOrTrend: "hybrid",
    visibleByDefault: false,
    requiresGuardrail: true,
    minSample: 50,
    minNEff: 30,
    maxFreshnessHours: 24,
    requiresAnonymityGuardrail: true,
    exportable: true,
    uiVariant: "table_column",
    defaultSlot: "details",
    defaultSortOrder: 0,
    isWiredToReadModel: false,
    isWiredToUI: false,
  },
  minimum_cohort_applied: {
    id: "minimum_cohort_applied",
    name: "Minimum Cohort Applied",
    shortDescription: "Métrica: Minimum Cohort Applied",
    origin: "system",
    allowedAudience: ["results", "admin"],
    level: "base",
    outputType: "number",
    family: "rigor",
    surfaces: ['admin_registry'],
    status: "pending_instrumentation",
    staticOrTrend: "hybrid",
    visibleByDefault: false,
    requiresGuardrail: true,
    minSample: 50,
    minNEff: 30,
    maxFreshnessHours: 24,
    requiresAnonymityGuardrail: true,
    exportable: true,
    uiVariant: "table_column",
    defaultSlot: "details",
    defaultSortOrder: 0,
    isWiredToReadModel: false,
    isWiredToUI: false,
  },
  sample_quality_label: {
    id: "sample_quality_label",
    name: "Sample Quality Label",
    shortDescription: "Métrica: Sample Quality Label",
    origin: "system",
    allowedAudience: ["results", "admin"],
    level: "base",
    outputType: "label",
    family: "depth",
    surfaces: ['admin_registry'],
    status: "pending_instrumentation",
    staticOrTrend: "hybrid",
    visibleByDefault: false,
    requiresGuardrail: true,
    minSample: 50,
    minNEff: 30,
    maxFreshnessHours: 24,
    requiresAnonymityGuardrail: true,
    exportable: true,
    uiVariant: "editorial_chip",
    defaultSlot: "details",
    defaultSortOrder: 0,
    isWiredToReadModel: false,
    isWiredToUI: false,
  },
  microdetail_locked: {
    id: "microdetail_locked",
    name: "Microdetail Locked",
    shortDescription: "Métrica: Microdetail Locked",
    origin: "system",
    allowedAudience: ["results", "admin"],
    level: "base",
    outputType: "number",
    family: "rigor",
    surfaces: ['admin_registry'],
    status: "pending_instrumentation",
    staticOrTrend: "hybrid",
    visibleByDefault: false,
    requiresGuardrail: true,
    minSample: 50,
    minNEff: 30,
    maxFreshnessHours: 24,
    requiresAnonymityGuardrail: true,
    exportable: true,
    uiVariant: "table_column",
    defaultSlot: "details",
    defaultSortOrder: 0,
    isWiredToReadModel: false,
    isWiredToUI: false,
  },
  data_mode_label: {
    id: "data_mode_label",
    name: "Data Mode Label",
    shortDescription: "Métrica: Data Mode Label",
    origin: "system",
    allowedAudience: ["results", "admin"],
    level: "base",
    outputType: "label",
    family: "rigor",
    surfaces: ['admin_registry'],
    status: "pending_instrumentation",
    staticOrTrend: "hybrid",
    visibleByDefault: false,
    requiresGuardrail: true,
    minSample: 50,
    minNEff: 30,
    maxFreshnessHours: 24,
    requiresAnonymityGuardrail: true,
    exportable: true,
    uiVariant: "editorial_chip",
    defaultSlot: "details",
    defaultSortOrder: 0,
    isWiredToReadModel: false,
    isWiredToUI: false,
  },
  weighted_preference_share: {
    id: "weighted_preference_share",
    name: "Weighted Preference Share",
    shortDescription: "Métrica: Weighted Preference Share",
    origin: "versus",
    allowedAudience: ["intelligence", "admin"],
    level: "advanced",
    outputType: "interval",
    family: "market",
    surfaces: ['b2b_benchmark_table','admin_registry'],
    status: "live",
    staticOrTrend: "hybrid",
    visibleByDefault: true,
    requiresGuardrail: true,
    minSample: 50,
    minNEff: 30,
    maxFreshnessHours: 24,
    requiresAnonymityGuardrail: true,
    exportable: true,
    uiVariant: "kpi_card",
    defaultSlot: "hero",
    defaultSortOrder: 0,
    isWiredToReadModel: false,
    isWiredToUI: false,
  },
  weighted_win_rate: {
    id: "weighted_win_rate",
    name: "Weighted Win Rate",
    shortDescription: "Métrica: Weighted Win Rate",
    origin: "system",
    allowedAudience: ["intelligence", "admin"],
    level: "advanced",
    outputType: "interval",
    family: "behavior",
    surfaces: ['b2b_benchmark_table','admin_registry'],
    status: "live",
    staticOrTrend: "hybrid",
    visibleByDefault: true,
    requiresGuardrail: true,
    minSample: 50,
    minNEff: 30,
    maxFreshnessHours: 24,
    requiresAnonymityGuardrail: true,
    exportable: true,
    uiVariant: "table_column",
    defaultSlot: "hero",
    defaultSortOrder: 0,
    isWiredToReadModel: false,
    isWiredToUI: false,
  },
  leader_rank: {
    id: "leader_rank",
    name: "Leader Rank",
    shortDescription: "Métrica: Leader Rank",
    origin: "versus",
    allowedAudience: ["intelligence", "admin"],
    level: "advanced",
    outputType: "number",
    family: "market",
    surfaces: ['b2b_benchmark_table','admin_registry'],
    status: "live",
    staticOrTrend: "hybrid",
    visibleByDefault: true,
    requiresGuardrail: true,
    minSample: 50,
    minNEff: 30,
    maxFreshnessHours: 24,
    requiresAnonymityGuardrail: true,
    exportable: true,
    uiVariant: "table_column",
    defaultSlot: "hero",
    defaultSortOrder: 0,
    isWiredToReadModel: false,
    isWiredToUI: false,
  },
  margin_vs_second: {
    id: "margin_vs_second",
    name: "Margin Vs Second",
    shortDescription: "Métrica: Margin Vs Second",
    origin: "system",
    allowedAudience: ["intelligence", "admin"],
    level: "advanced",
    outputType: "interval",
    family: "rigor",
    surfaces: ['b2b_benchmark_table','admin_registry'],
    status: "live",
    staticOrTrend: "hybrid",
    visibleByDefault: true,
    requiresGuardrail: true,
    minSample: 50,
    minNEff: 30,
    maxFreshnessHours: 24,
    requiresAnonymityGuardrail: true,
    exportable: true,
    uiVariant: "table_column",
    defaultSlot: "hero",
    defaultSortOrder: 0,
    isWiredToReadModel: false,
    isWiredToUI: false,
  },
  leaderboard_position_change: {
    id: "leaderboard_position_change",
    name: "Leaderboard Position Change",
    shortDescription: "Métrica: Leaderboard Position Change",
    origin: "versus",
    allowedAudience: ["intelligence", "admin"],
    level: "advanced",
    outputType: "number",
    family: "market",
    surfaces: ['admin_registry'],
    status: "pending_instrumentation",
    staticOrTrend: "hybrid",
    visibleByDefault: false,
    requiresGuardrail: true,
    minSample: 50,
    minNEff: 30,
    maxFreshnessHours: 24,
    requiresAnonymityGuardrail: true,
    exportable: true,
    uiVariant: "table_column",
    defaultSlot: "details",
    defaultSortOrder: 0,
    isWiredToReadModel: false,
    isWiredToUI: false,
  },
  time_decay_momentum: {
    id: "time_decay_momentum",
    name: "Time Decay Momentum",
    shortDescription: "Métrica: Time Decay Momentum",
    origin: "system",
    allowedAudience: ["intelligence", "admin"],
    level: "advanced",
    outputType: "number",
    family: "rigor",
    surfaces: ['b2b_benchmark_table','admin_registry'],
    status: "live",
    staticOrTrend: "hybrid",
    visibleByDefault: true,
    requiresGuardrail: true,
    minSample: 50,
    minNEff: 30,
    maxFreshnessHours: 24,
    requiresAnonymityGuardrail: true,
    exportable: true,
    uiVariant: "table_column",
    defaultSlot: "hero",
    defaultSortOrder: 0,
    isWiredToReadModel: false,
    isWiredToUI: false,
  },
  trend_acceleration: {
    id: "trend_acceleration",
    name: "Trend Acceleration",
    shortDescription: "Aceleración del cambio de share del líder día a día (derivada del rollup).",
    origin: "system",
    allowedAudience: ["intelligence", "admin"],
    level: "advanced",
    outputType: "number",
    family: "rigor",
    surfaces: ['admin_registry', 'results_hero'],
    status: "live",
    staticOrTrend: "trend",
    visibleByDefault: true,
    requiresGuardrail: true,
    minSample: 50,
    minNEff: 30,
    maxFreshnessHours: 24,
    requiresAnonymityGuardrail: true,
    exportable: true,
    uiVariant: "table_column",
    defaultSlot: "details",
    defaultSortOrder: 0,
    isWiredToReadModel: true,
    isWiredToUI: true,
  },
  trend_direction: {
    id: "trend_direction",
    name: "Trend Direction",
    shortDescription: "Dirección de la tendencia del líder (sube/baja/plana) calculada desde rollup.",
    origin: "system",
    allowedAudience: ["intelligence", "admin"],
    level: "advanced",
    outputType: "number",
    family: "rigor",
    surfaces: ['admin_registry', 'results_hero'],
    status: "live",
    staticOrTrend: "trend",
    visibleByDefault: true,
    requiresGuardrail: true,
    minSample: 50,
    minNEff: 30,
    maxFreshnessHours: 24,
    requiresAnonymityGuardrail: true,
    exportable: true,
    uiVariant: "table_column",
    defaultSlot: "details",
    defaultSortOrder: 0,
    isWiredToReadModel: true,
    isWiredToUI: true,
  },
  champion_retention_rate: {
    id: "champion_retention_rate",
    name: "Champion Retention Rate",
    shortDescription: "Métrica: Champion Retention Rate",
    origin: "tournament",
    allowedAudience: ["intelligence", "admin"],
    level: "advanced",
    outputType: "interval",
    family: "behavior",
    surfaces: ['admin_registry'],
    status: "pending_instrumentation",
    staticOrTrend: "hybrid",
    visibleByDefault: false,
    requiresGuardrail: true,
    minSample: 50,
    minNEff: 30,
    maxFreshnessHours: 24,
    requiresAnonymityGuardrail: true,
    exportable: true,
    uiVariant: "table_column",
    defaultSlot: "details",
    defaultSortOrder: 0,
    isWiredToReadModel: false,
    isWiredToUI: false,
  },
  upset_rate: {
    id: "upset_rate",
    name: "Upset Rate",
    shortDescription: "Métrica: Upset Rate",
    origin: "system",
    allowedAudience: ["intelligence", "admin"],
    level: "advanced",
    outputType: "interval",
    family: "behavior",
    surfaces: ['admin_registry'],
    status: "pending_instrumentation",
    staticOrTrend: "hybrid",
    visibleByDefault: false,
    requiresGuardrail: true,
    minSample: 50,
    minNEff: 30,
    maxFreshnessHours: 24,
    requiresAnonymityGuardrail: true,
    exportable: true,
    uiVariant: "table_column",
    defaultSlot: "details",
    defaultSortOrder: 0,
    isWiredToReadModel: false,
    isWiredToUI: false,
  },
  comparative_preference_gap: {
    id: "comparative_preference_gap",
    name: "Comparative Preference Gap",
    shortDescription: "Métrica: Comparative Preference Gap",
    origin: "versus",
    allowedAudience: ["intelligence", "admin"],
    level: "advanced",
    outputType: "interval",
    family: "market",
    surfaces: ['admin_registry'],
    status: "pending_instrumentation",
    staticOrTrend: "hybrid",
    visibleByDefault: false,
    requiresGuardrail: true,
    minSample: 50,
    minNEff: 30,
    maxFreshnessHours: 24,
    requiresAnonymityGuardrail: true,
    exportable: true,
    uiVariant: "table_column",
    defaultSlot: "details",
    defaultSortOrder: 0,
    isWiredToReadModel: false,
    isWiredToUI: false,
  },
  total_effective_weight: {
    id: "total_effective_weight",
    name: "Total Effective Weight",
    shortDescription: "Métrica: Total Effective Weight",
    origin: "system",
    allowedAudience: ["intelligence", "admin"],
    level: "advanced",
    outputType: "number",
    family: "rigor",
    surfaces: ['admin_registry'],
    status: "pending_instrumentation",
    staticOrTrend: "hybrid",
    visibleByDefault: false,
    requiresGuardrail: true,
    minSample: 50,
    minNEff: 30,
    maxFreshnessHours: 24,
    requiresAnonymityGuardrail: true,
    exportable: true,
    uiVariant: "table_column",
    defaultSlot: "details",
    defaultSortOrder: 0,
    isWiredToReadModel: false,
    isWiredToUI: false,
  },
  n_eff: {
    id: "n_eff",
    name: "N Efectivo",
    shortDescription: "Métrica: N Efectivo",
    origin: "system",
    allowedAudience: ["intelligence", "admin"],
    level: "advanced",
    outputType: "number",
    family: "rigor",
    surfaces: ['b2b_benchmark_table','admin_registry'],
    status: "pending_instrumentation",
    staticOrTrend: "hybrid",
    visibleByDefault: false,
    requiresGuardrail: true,
    minSample: 50,
    minNEff: 30,
    maxFreshnessHours: 24,
    requiresAnonymityGuardrail: true,
    exportable: true,
    uiVariant: "table_column",
    defaultSlot: "hero",
    defaultSortOrder: 0,
    isWiredToReadModel: false,
    isWiredToUI: false,
  },
  wilson_lower_bound: {
    id: "wilson_lower_bound",
    name: "Wilson Lower Bound",
    shortDescription: "Métrica: Wilson Lower Bound",
    origin: "system",
    allowedAudience: ["intelligence", "admin"],
    level: "advanced",
    outputType: "number",
    family: "rigor",
    surfaces: ['b2b_benchmark_table','admin_registry'],
    status: "live",
    staticOrTrend: "hybrid",
    visibleByDefault: true,
    requiresGuardrail: true,
    minSample: 50,
    minNEff: 30,
    maxFreshnessHours: 24,
    requiresAnonymityGuardrail: true,
    exportable: true,
    uiVariant: "table_column",
    defaultSlot: "hero",
    defaultSortOrder: 0,
    isWiredToReadModel: false,
    isWiredToUI: false,
  },
  wilson_upper_bound: {
    id: "wilson_upper_bound",
    name: "Wilson Upper Bound",
    shortDescription: "Métrica: Wilson Upper Bound",
    origin: "system",
    allowedAudience: ["intelligence", "admin"],
    level: "advanced",
    outputType: "number",
    family: "rigor",
    surfaces: ['b2b_benchmark_table','admin_registry'],
    status: "live",
    staticOrTrend: "hybrid",
    visibleByDefault: true,
    requiresGuardrail: true,
    minSample: 50,
    minNEff: 30,
    maxFreshnessHours: 24,
    requiresAnonymityGuardrail: true,
    exportable: true,
    uiVariant: "table_column",
    defaultSlot: "hero",
    defaultSortOrder: 0,
    isWiredToReadModel: false,
    isWiredToUI: false,
  },
  confidence_level: {
    id: "confidence_level",
    name: "Confidence Level",
    shortDescription: "Métrica: Confidence Level",
    origin: "system",
    allowedAudience: ["intelligence", "admin"],
    level: "advanced",
    outputType: "number",
    family: "rigor",
    surfaces: ['admin_registry'],
    status: "pending_instrumentation",
    staticOrTrend: "hybrid",
    visibleByDefault: false,
    requiresGuardrail: true,
    minSample: 50,
    minNEff: 30,
    maxFreshnessHours: 24,
    requiresAnonymityGuardrail: true,
    exportable: true,
    uiVariant: "table_column",
    defaultSlot: "details",
    defaultSortOrder: 0,
    isWiredToReadModel: false,
    isWiredToUI: false,
  },
  entropy_normalized: {
    id: "entropy_normalized",
    name: "Entropy Normalized",
    shortDescription: "Métrica: Entropy Normalized",
    origin: "system",
    allowedAudience: ["intelligence", "admin"],
    level: "advanced",
    outputType: "number",
    family: "rigor",
    surfaces: ['b2b_overview_trends','admin_registry'],
    status: "live",
    staticOrTrend: "hybrid",
    visibleByDefault: true,
    requiresGuardrail: true,
    minSample: 50,
    minNEff: 30,
    maxFreshnessHours: 24,
    requiresAnonymityGuardrail: true,
    exportable: true,
    uiVariant: "table_column",
    defaultSlot: "hero",
    defaultSortOrder: 0,
    isWiredToReadModel: false,
    isWiredToUI: false,
  },
  mass_to_revert: {
    id: "mass_to_revert",
    name: "Mass To Revert",
    shortDescription: "Cuántos duelos efectivos tendrían que voltearse para revertir el liderazgo actual.",
    origin: "system",
    allowedAudience: ["intelligence", "admin", "results"],
    level: "advanced",
    outputType: "number",
    family: "rigor",
    surfaces: ['admin_registry', 'results_hero'],
    status: "live",
    staticOrTrend: "static",
    visibleByDefault: true,
    requiresGuardrail: true,
    minSample: 30,
    minNEff: 30,
    maxFreshnessHours: 24,
    requiresAnonymityGuardrail: true,
    exportable: true,
    uiVariant: "editorial_chip",
    defaultSlot: "hero",
    defaultSortOrder: 0,
    isWiredToReadModel: true,
    isWiredToUI: true,
  },
  stability_label: {
    id: "stability_label",
    name: "Stability Label",
    shortDescription: "Métrica: Stability Label",
    origin: "system",
    allowedAudience: ["intelligence", "admin"],
    level: "advanced",
    outputType: "label",
    family: "rigor",
    surfaces: ['b2b_benchmark_table','admin_registry'],
    status: "live",
    staticOrTrend: "hybrid",
    visibleByDefault: true,
    requiresGuardrail: true,
    minSample: 50,
    minNEff: 30,
    maxFreshnessHours: 24,
    requiresAnonymityGuardrail: true,
    exportable: true,
    uiVariant: "editorial_chip",
    defaultSlot: "hero",
    defaultSortOrder: 0,
    isWiredToReadModel: false,
    isWiredToUI: false,
  },
  source_mode: {
    id: "source_mode",
    name: "Source Mode",
    shortDescription: "Métrica: Source Mode",
    origin: "system",
    allowedAudience: ["intelligence", "admin"],
    level: "advanced",
    outputType: "number",
    family: "rigor",
    surfaces: ['admin_registry'],
    status: "pending_instrumentation",
    staticOrTrend: "hybrid",
    visibleByDefault: false,
    requiresGuardrail: true,
    minSample: 50,
    minNEff: 30,
    maxFreshnessHours: 24,
    requiresAnonymityGuardrail: true,
    exportable: true,
    uiVariant: "table_column",
    defaultSlot: "details",
    defaultSortOrder: 0,
    isWiredToReadModel: false,
    isWiredToUI: false,
  },
  commercial_eligibility_label: {
    id: "commercial_eligibility_label",
    name: "Commercial Eligibility Label",
    shortDescription: "Métrica: Commercial Eligibility Label",
    origin: "system",
    allowedAudience: ["intelligence", "admin"],
    level: "advanced",
    outputType: "label",
    family: "rigor",
    surfaces: ['b2b_reports_export','admin_registry'],
    status: "pending_instrumentation",
    staticOrTrend: "hybrid",
    visibleByDefault: false,
    requiresGuardrail: true,
    minSample: 50,
    minNEff: 30,
    maxFreshnessHours: 24,
    requiresAnonymityGuardrail: true,
    exportable: true,
    uiVariant: "editorial_chip",
    defaultSlot: "hero",
    defaultSortOrder: 0,
    isWiredToReadModel: false,
    isWiredToUI: false,
  },
  mean_score: {
    id: "mean_score",
    name: "Mean Score",
    shortDescription: "Métrica: Mean Score",
    origin: "system",
    allowedAudience: ["intelligence", "admin"],
    level: "advanced",
    outputType: "score",
    family: "depth",
    surfaces: ['admin_registry'],
    status: "pending_instrumentation",
    staticOrTrend: "hybrid",
    visibleByDefault: false,
    requiresGuardrail: true,
    minSample: 50,
    minNEff: 30,
    maxFreshnessHours: 24,
    requiresAnonymityGuardrail: true,
    exportable: true,
    uiVariant: "kpi_card",
    defaultSlot: "details",
    defaultSortOrder: 0,
    isWiredToReadModel: false,
    isWiredToUI: false,
  },
  bayesian_mean_score: {
    id: "bayesian_mean_score",
    name: "Bayesian Mean Score",
    shortDescription: "Métrica: Bayesian Mean Score",
    origin: "system",
    allowedAudience: ["intelligence", "admin"],
    level: "advanced",
    outputType: "score",
    family: "depth",
    surfaces: ['admin_registry'],
    status: "pending_instrumentation",
    staticOrTrend: "hybrid",
    visibleByDefault: false,
    requiresGuardrail: true,
    minSample: 50,
    minNEff: 30,
    maxFreshnessHours: 24,
    requiresAnonymityGuardrail: true,
    exportable: true,
    uiVariant: "kpi_card",
    defaultSlot: "details",
    defaultSortOrder: 0,
    isWiredToReadModel: false,
    isWiredToUI: false,
  },
  nps_score: {
    id: "nps_score",
    name: "NPS Score",
    shortDescription: "Métrica: NPS Score",
    origin: "depth",
    allowedAudience: ["intelligence", "admin"],
    level: "advanced",
    outputType: "score",
    family: "depth",
    surfaces: ['admin_registry'],
    status: "pending_instrumentation",
    staticOrTrend: "hybrid",
    visibleByDefault: false,
    requiresGuardrail: true,
    minSample: 50,
    minNEff: 30,
    maxFreshnessHours: 24,
    requiresAnonymityGuardrail: true,
    exportable: true,
    uiVariant: "kpi_card",
    defaultSlot: "details",
    defaultSortOrder: 0,
    isWiredToReadModel: false,
    isWiredToUI: false,
  },
  promoter_share: {
    id: "promoter_share",
    name: "Promoter Share",
    shortDescription: "Métrica: Promoter Share",
    origin: "system",
    allowedAudience: ["intelligence", "admin"],
    level: "advanced",
    outputType: "interval",
    family: "rigor",
    surfaces: ['admin_registry'],
    status: "pending_instrumentation",
    staticOrTrend: "hybrid",
    visibleByDefault: false,
    requiresGuardrail: true,
    minSample: 50,
    minNEff: 30,
    maxFreshnessHours: 24,
    requiresAnonymityGuardrail: true,
    exportable: true,
    uiVariant: "kpi_card",
    defaultSlot: "details",
    defaultSortOrder: 0,
    isWiredToReadModel: false,
    isWiredToUI: false,
  },
  passive_share: {
    id: "passive_share",
    name: "Passive Share",
    shortDescription: "Métrica: Passive Share",
    origin: "system",
    allowedAudience: ["intelligence", "admin"],
    level: "advanced",
    outputType: "interval",
    family: "rigor",
    surfaces: ['admin_registry'],
    status: "pending_instrumentation",
    staticOrTrend: "hybrid",
    visibleByDefault: false,
    requiresGuardrail: true,
    minSample: 50,
    minNEff: 30,
    maxFreshnessHours: 24,
    requiresAnonymityGuardrail: true,
    exportable: true,
    uiVariant: "kpi_card",
    defaultSlot: "details",
    defaultSortOrder: 0,
    isWiredToReadModel: false,
    isWiredToUI: false,
  },
  detractor_share: {
    id: "detractor_share",
    name: "Detractor Share",
    shortDescription: "Métrica: Detractor Share",
    origin: "system",
    allowedAudience: ["intelligence", "admin"],
    level: "advanced",
    outputType: "interval",
    family: "rigor",
    surfaces: ['admin_registry'],
    status: "pending_instrumentation",
    staticOrTrend: "hybrid",
    visibleByDefault: false,
    requiresGuardrail: true,
    minSample: 50,
    minNEff: 30,
    maxFreshnessHours: 24,
    requiresAnonymityGuardrail: true,
    exportable: true,
    uiVariant: "kpi_card",
    defaultSlot: "details",
    defaultSortOrder: 0,
    isWiredToReadModel: false,
    isWiredToUI: false,
  },
  top_box_share: {
    id: "top_box_share",
    name: "Top Box Share",
    shortDescription: "Métrica: Top Box Share",
    origin: "system",
    allowedAudience: ["intelligence", "admin"],
    level: "advanced",
    outputType: "interval",
    family: "rigor",
    surfaces: ['admin_registry'],
    status: "pending_instrumentation",
    staticOrTrend: "hybrid",
    visibleByDefault: false,
    requiresGuardrail: true,
    minSample: 50,
    minNEff: 30,
    maxFreshnessHours: 24,
    requiresAnonymityGuardrail: true,
    exportable: true,
    uiVariant: "kpi_card",
    defaultSlot: "details",
    defaultSortOrder: 0,
    isWiredToReadModel: false,
    isWiredToUI: false,
  },
  bottom_box_share: {
    id: "bottom_box_share",
    name: "Bottom Box Share",
    shortDescription: "Métrica: Bottom Box Share",
    origin: "system",
    allowedAudience: ["intelligence", "admin"],
    level: "advanced",
    outputType: "interval",
    family: "rigor",
    surfaces: ['admin_registry'],
    status: "pending_instrumentation",
    staticOrTrend: "hybrid",
    visibleByDefault: false,
    requiresGuardrail: true,
    minSample: 50,
    minNEff: 30,
    maxFreshnessHours: 24,
    requiresAnonymityGuardrail: true,
    exportable: true,
    uiVariant: "kpi_card",
    defaultSlot: "details",
    defaultSortOrder: 0,
    isWiredToReadModel: false,
    isWiredToUI: false,
  },
  attribute_mean_score: {
    id: "attribute_mean_score",
    name: "Attribute Mean Score",
    shortDescription: "Métrica: Attribute Mean Score",
    origin: "depth",
    allowedAudience: ["intelligence", "admin"],
    level: "advanced",
    outputType: "score",
    family: "depth",
    surfaces: ['admin_registry'],
    status: "pending_instrumentation",
    staticOrTrend: "hybrid",
    visibleByDefault: false,
    requiresGuardrail: true,
    minSample: 50,
    minNEff: 30,
    maxFreshnessHours: 24,
    requiresAnonymityGuardrail: true,
    exportable: true,
    uiVariant: "kpi_card",
    defaultSlot: "details",
    defaultSortOrder: 0,
    isWiredToReadModel: false,
    isWiredToUI: false,
  },
  attribute_dispersion: {
    id: "attribute_dispersion",
    name: "Attribute Dispersion",
    shortDescription: "Métrica: Attribute Dispersion",
    origin: "depth",
    allowedAudience: ["intelligence", "admin"],
    level: "advanced",
    outputType: "number",
    family: "depth",
    surfaces: ['admin_registry'],
    status: "pending_instrumentation",
    staticOrTrend: "hybrid",
    visibleByDefault: false,
    requiresGuardrail: true,
    minSample: 50,
    minNEff: 30,
    maxFreshnessHours: 24,
    requiresAnonymityGuardrail: true,
    exportable: true,
    uiVariant: "table_column",
    defaultSlot: "details",
    defaultSortOrder: 0,
    isWiredToReadModel: false,
    isWiredToUI: false,
  },
  attribute_driver_weight: {
    id: "attribute_driver_weight",
    name: "Attribute Driver Weight",
    shortDescription: "Métrica: Attribute Driver Weight",
    origin: "depth",
    allowedAudience: ["intelligence", "admin"],
    level: "advanced",
    outputType: "number",
    family: "depth",
    surfaces: ['admin_registry'],
    status: "pending_instrumentation",
    staticOrTrend: "hybrid",
    visibleByDefault: false,
    requiresGuardrail: true,
    minSample: 50,
    minNEff: 30,
    maxFreshnessHours: 24,
    requiresAnonymityGuardrail: true,
    exportable: true,
    uiVariant: "table_column",
    defaultSlot: "details",
    defaultSortOrder: 0,
    isWiredToReadModel: false,
    isWiredToUI: false,
  },
  perceptual_polarization_index: {
    id: "perceptual_polarization_index",
    name: "Perceptual Polarization Index",
    shortDescription: "Métrica: Perceptual Polarization Index",
    origin: "system",
    allowedAudience: ["intelligence", "admin"],
    level: "advanced",
    outputType: "score",
    family: "rigor",
    surfaces: ['admin_registry'],
    status: "pending_instrumentation",
    staticOrTrend: "hybrid",
    visibleByDefault: false,
    requiresGuardrail: true,
    minSample: 50,
    minNEff: 30,
    maxFreshnessHours: 24,
    requiresAnonymityGuardrail: true,
    exportable: true,
    uiVariant: "table_column",
    defaultSlot: "details",
    defaultSortOrder: 0,
    isWiredToReadModel: false,
    isWiredToUI: false,
  },
  preference_quality_gap: {
    id: "preference_quality_gap",
    name: "Preference Quality Gap",
    shortDescription: "Métrica: Preference Quality Gap",
    origin: "versus",
    allowedAudience: ["intelligence", "admin"],
    level: "advanced",
    outputType: "interval",
    family: "market",
    surfaces: ['b2b_deep_dive_body','admin_registry'],
    status: "pending_instrumentation",
    staticOrTrend: "hybrid",
    visibleByDefault: false,
    requiresGuardrail: true,
    minSample: 50,
    minNEff: 30,
    maxFreshnessHours: 24,
    requiresAnonymityGuardrail: true,
    exportable: true,
    uiVariant: "table_column",
    defaultSlot: "hero",
    defaultSortOrder: 0,
    isWiredToReadModel: false,
    isWiredToUI: false,
  },
  attribute_gap_vs_competitor: {
    id: "attribute_gap_vs_competitor",
    name: "Attribute Gap Vs Competitor",
    shortDescription: "Métrica: Attribute Gap Vs Competitor",
    origin: "depth",
    allowedAudience: ["intelligence", "admin"],
    level: "advanced",
    outputType: "interval",
    family: "depth",
    surfaces: ['admin_registry'],
    status: "pending_instrumentation",
    staticOrTrend: "hybrid",
    visibleByDefault: false,
    requiresGuardrail: true,
    minSample: 50,
    minNEff: 30,
    maxFreshnessHours: 24,
    requiresAnonymityGuardrail: true,
    exportable: true,
    uiVariant: "table_column",
    defaultSlot: "details",
    defaultSortOrder: 0,
    isWiredToReadModel: false,
    isWiredToUI: false,
  },
  topic_heat_index: {
    id: "topic_heat_index",
    name: "Topic Heat Index",
    shortDescription: "Métrica: Topic Heat Index",
    origin: "news",
    allowedAudience: ["intelligence", "admin"],
    level: "advanced",
    outputType: "score",
    family: "actualidad",
    surfaces: ['b2b_overview_trends','admin_registry'],
    status: "live",
    staticOrTrend: "hybrid",
    visibleByDefault: true,
    requiresGuardrail: true,
    minSample: 50,
    minNEff: 30,
    maxFreshnessHours: 24,
    requiresAnonymityGuardrail: true,
    exportable: true,
    uiVariant: "table_column",
    defaultSlot: "hero",
    defaultSortOrder: 0,
    isWiredToReadModel: false,
    isWiredToUI: false,
  },
  topic_resonance_index: {
    id: "topic_resonance_index",
    name: "Topic Resonance Index",
    shortDescription: "Métrica: Topic Resonance Index",
    origin: "news",
    allowedAudience: ["intelligence", "admin"],
    level: "advanced",
    outputType: "score",
    family: "actualidad",
    surfaces: ['admin_registry'],
    status: "pending_instrumentation",
    staticOrTrend: "hybrid",
    visibleByDefault: false,
    requiresGuardrail: true,
    minSample: 50,
    minNEff: 30,
    maxFreshnessHours: 24,
    requiresAnonymityGuardrail: true,
    exportable: true,
    uiVariant: "table_column",
    defaultSlot: "details",
    defaultSortOrder: 0,
    isWiredToReadModel: false,
    isWiredToUI: false,
  },
  topic_polarization_index: {
    id: "topic_polarization_index",
    name: "Topic Polarization Index",
    shortDescription: "Métrica: Topic Polarization Index",
    origin: "news",
    allowedAudience: ["intelligence", "admin"],
    level: "advanced",
    outputType: "score",
    family: "actualidad",
    surfaces: ['admin_registry'],
    status: "pending_instrumentation",
    staticOrTrend: "hybrid",
    visibleByDefault: false,
    requiresGuardrail: true,
    minSample: 50,
    minNEff: 30,
    maxFreshnessHours: 24,
    requiresAnonymityGuardrail: true,
    exportable: true,
    uiVariant: "table_column",
    defaultSlot: "details",
    defaultSortOrder: 0,
    isWiredToReadModel: false,
    isWiredToUI: false,
  },
  topic_consensus_index: {
    id: "topic_consensus_index",
    name: "Topic Consensus Index",
    shortDescription: "Métrica: Topic Consensus Index",
    origin: "news",
    allowedAudience: ["intelligence", "admin"],
    level: "advanced",
    outputType: "score",
    family: "actualidad",
    surfaces: ['admin_registry'],
    status: "pending_instrumentation",
    staticOrTrend: "hybrid",
    visibleByDefault: false,
    requiresGuardrail: true,
    minSample: 50,
    minNEff: 30,
    maxFreshnessHours: 24,
    requiresAnonymityGuardrail: true,
    exportable: true,
    uiVariant: "table_column",
    defaultSlot: "details",
    defaultSortOrder: 0,
    isWiredToReadModel: false,
    isWiredToUI: false,
  },
  reaction_latency_minutes: {
    id: "reaction_latency_minutes",
    name: "Reaction Latency Minutes",
    shortDescription: "Métrica: Reaction Latency Minutes",
    origin: "system",
    allowedAudience: ["intelligence", "admin"],
    level: "advanced",
    outputType: "number",
    family: "rigor",
    surfaces: ['admin_registry'],
    status: "pending_instrumentation",
    staticOrTrend: "hybrid",
    visibleByDefault: false,
    requiresGuardrail: true,
    minSample: 50,
    minNEff: 30,
    maxFreshnessHours: 24,
    requiresAnonymityGuardrail: true,
    exportable: true,
    uiVariant: "table_column",
    defaultSlot: "details",
    defaultSortOrder: 0,
    isWiredToReadModel: false,
    isWiredToUI: false,
  },
  topic_half_life_days: {
    id: "topic_half_life_days",
    name: "Topic Half Life Days",
    shortDescription: "Métrica: Topic Half Life Days",
    origin: "news",
    allowedAudience: ["intelligence", "admin"],
    level: "advanced",
    outputType: "number",
    family: "actualidad",
    surfaces: ['admin_registry'],
    status: "pending_instrumentation",
    staticOrTrend: "hybrid",
    visibleByDefault: false,
    requiresGuardrail: true,
    minSample: 50,
    minNEff: 30,
    maxFreshnessHours: 24,
    requiresAnonymityGuardrail: true,
    exportable: true,
    uiVariant: "table_column",
    defaultSlot: "details",
    defaultSortOrder: 0,
    isWiredToReadModel: false,
    isWiredToUI: false,
  },
  topic_persistence_label: {
    id: "topic_persistence_label",
    name: "Topic Persistence Label",
    shortDescription: "Métrica: Topic Persistence Label",
    origin: "news",
    allowedAudience: ["intelligence", "admin"],
    level: "advanced",
    outputType: "label",
    family: "actualidad",
    surfaces: ['admin_registry'],
    status: "pending_instrumentation",
    staticOrTrend: "hybrid",
    visibleByDefault: false,
    requiresGuardrail: true,
    minSample: 50,
    minNEff: 30,
    maxFreshnessHours: 24,
    requiresAnonymityGuardrail: true,
    exportable: true,
    uiVariant: "editorial_chip",
    defaultSlot: "details",
    defaultSortOrder: 0,
    isWiredToReadModel: false,
    isWiredToUI: false,
  },
  news_to_entity_impact: {
    id: "news_to_entity_impact",
    name: "News To Entity Impact",
    shortDescription: "Métrica: News To Entity Impact",
    origin: "news",
    allowedAudience: ["intelligence", "admin"],
    level: "advanced",
    outputType: "entity_ref",
    family: "actualidad",
    surfaces: ['admin_registry'],
    status: "pending_instrumentation",
    staticOrTrend: "hybrid",
    visibleByDefault: false,
    requiresGuardrail: true,
    minSample: 50,
    minNEff: 30,
    maxFreshnessHours: 24,
    requiresAnonymityGuardrail: true,
    exportable: true,
    uiVariant: "table_column",
    defaultSlot: "details",
    defaultSortOrder: 0,
    isWiredToReadModel: false,
    isWiredToUI: false,
  },
  entity_context_sensitivity: {
    id: "entity_context_sensitivity",
    name: "Entity Context Sensitivity",
    shortDescription: "Sensibilidad contextual: dispersión del impacto del score entre segmentos demográficos.",
    origin: "system",
    allowedAudience: ["intelligence", "admin"],
    level: "advanced",
    outputType: "score",
    family: "rigor",
    surfaces: ['admin_registry', 'b2b_deep_dive_body'],
    status: "live",
    staticOrTrend: "hybrid",
    visibleByDefault: true,
    requiresGuardrail: true,
    minSample: 50,
    minNEff: 30,
    maxFreshnessHours: 24,
    requiresAnonymityGuardrail: true,
    exportable: true,
    uiVariant: "kpi_card",
    defaultSlot: "details",
    defaultSortOrder: 0,
    isWiredToReadModel: true,
    isWiredToUI: true,
  },
  reputation_risk_index: {
    id: "reputation_risk_index",
    name: "Reputation Risk Index",
    shortDescription: "Métrica: Reputation Risk Index",
    origin: "system",
    allowedAudience: ["intelligence", "admin"],
    level: "advanced",
    outputType: "score",
    family: "rigor",
    surfaces: ['b2b_alerts_feed','admin_registry'],
    status: "pending_instrumentation",
    staticOrTrend: "hybrid",
    visibleByDefault: false,
    requiresGuardrail: true,
    minSample: 50,
    minNEff: 30,
    maxFreshnessHours: 24,
    requiresAnonymityGuardrail: true,
    exportable: true,
    uiVariant: "table_column",
    defaultSlot: "hero",
    defaultSortOrder: 0,
    isWiredToReadModel: false,
    isWiredToUI: false,
  },
  topic_shift_vs_baseline: {
    id: "topic_shift_vs_baseline",
    name: "Topic Shift Vs Baseline",
    shortDescription: "Métrica: Topic Shift Vs Baseline",
    origin: "news",
    allowedAudience: ["intelligence", "admin"],
    level: "advanced",
    outputType: "number",
    family: "actualidad",
    surfaces: ['admin_registry'],
    status: "pending_instrumentation",
    staticOrTrend: "hybrid",
    visibleByDefault: false,
    requiresGuardrail: true,
    minSample: 50,
    minNEff: 30,
    maxFreshnessHours: 24,
    requiresAnonymityGuardrail: true,
    exportable: true,
    uiVariant: "table_column",
    defaultSlot: "details",
    defaultSortOrder: 0,
    isWiredToReadModel: false,
    isWiredToUI: false,
  },
  segment_preference_share: {
    id: "segment_preference_share",
    name: "Segment Preference Share",
    shortDescription: "Métrica: Segment Preference Share",
    origin: "versus",
    allowedAudience: ["intelligence", "admin"],
    level: "advanced",
    outputType: "interval",
    family: "market",
    surfaces: ['admin_registry'],
    status: "pending_instrumentation",
    staticOrTrend: "hybrid",
    visibleByDefault: false,
    requiresGuardrail: true,
    minSample: 50,
    minNEff: 30,
    maxFreshnessHours: 24,
    requiresAnonymityGuardrail: true,
    exportable: true,
    uiVariant: "kpi_card",
    defaultSlot: "details",
    defaultSortOrder: 0,
    isWiredToReadModel: false,
    isWiredToUI: false,
  },
  segment_lift_vs_total: {
    id: "segment_lift_vs_total",
    name: "Segment Lift Vs Total",
    shortDescription: "Métrica: Segment Lift Vs Total",
    origin: "system",
    allowedAudience: ["intelligence", "admin"],
    level: "advanced",
    outputType: "number",
    family: "segments",
    surfaces: ['admin_registry'],
    status: "pending_instrumentation",
    staticOrTrend: "hybrid",
    visibleByDefault: false,
    requiresGuardrail: true,
    minSample: 50,
    minNEff: 30,
    maxFreshnessHours: 24,
    requiresAnonymityGuardrail: true,
    exportable: true,
    uiVariant: "table_column",
    defaultSlot: "details",
    defaultSortOrder: 0,
    isWiredToReadModel: false,
    isWiredToUI: false,
  },
  generation_gap_index: {
    id: "generation_gap_index",
    name: "Generation Gap Index",
    shortDescription: "Métrica: Generation Gap Index",
    origin: "system",
    allowedAudience: ["intelligence", "admin"],
    level: "advanced",
    outputType: "score",
    family: "segments",
    surfaces: ['b2b_deep_dive_body','admin_registry'],
    status: "live",
    staticOrTrend: "hybrid",
    visibleByDefault: true,
    requiresGuardrail: true,
    minSample: 50,
    minNEff: 30,
    maxFreshnessHours: 24,
    requiresAnonymityGuardrail: true,
    exportable: true,
    uiVariant: "table_column",
    defaultSlot: "hero",
    defaultSortOrder: 0,
    isWiredToReadModel: false,
    isWiredToUI: false,
  },
  gender_gap_index: {
    id: "gender_gap_index",
    name: "Gender Gap Index",
    shortDescription: "Métrica: Gender Gap Index",
    origin: "system",
    allowedAudience: ["intelligence", "admin"],
    level: "advanced",
    outputType: "score",
    family: "segments",
    surfaces: ['admin_registry'],
    status: "pending_instrumentation",
    staticOrTrend: "hybrid",
    visibleByDefault: false,
    requiresGuardrail: true,
    minSample: 50,
    minNEff: 30,
    maxFreshnessHours: 24,
    requiresAnonymityGuardrail: true,
    exportable: true,
    uiVariant: "table_column",
    defaultSlot: "details",
    defaultSortOrder: 0,
    isWiredToReadModel: false,
    isWiredToUI: false,
  },
  territory_gap_index: {
    id: "territory_gap_index",
    name: "Territory Gap Index",
    shortDescription: "Métrica: Territory Gap Index",
    origin: "system",
    allowedAudience: ["intelligence", "admin"],
    level: "advanced",
    outputType: "score",
    family: "segments",
    surfaces: ['admin_registry'],
    status: "pending_instrumentation",
    staticOrTrend: "hybrid",
    visibleByDefault: false,
    requiresGuardrail: true,
    minSample: 50,
    minNEff: 30,
    maxFreshnessHours: 24,
    requiresAnonymityGuardrail: true,
    exportable: true,
    uiVariant: "table_column",
    defaultSlot: "details",
    defaultSortOrder: 0,
    isWiredToReadModel: false,
    isWiredToUI: false,
  },
  verification_gap_index: {
    id: "verification_gap_index",
    name: "Verification Gap Index",
    shortDescription: "Métrica: Verification Gap Index",
    origin: "system",
    allowedAudience: ["intelligence", "admin"],
    level: "advanced",
    outputType: "score",
    family: "segments",
    surfaces: ['admin_registry'],
    status: "pending_instrumentation",
    staticOrTrend: "hybrid",
    visibleByDefault: false,
    requiresGuardrail: true,
    minSample: 50,
    minNEff: 30,
    maxFreshnessHours: 24,
    requiresAnonymityGuardrail: true,
    exportable: true,
    uiVariant: "table_column",
    defaultSlot: "details",
    defaultSortOrder: 0,
    isWiredToReadModel: false,
    isWiredToUI: false,
  },
  segment_polarization_index: {
    id: "segment_polarization_index",
    name: "Segment Polarization Index",
    shortDescription: "Métrica: Segment Polarization Index",
    origin: "system",
    allowedAudience: ["intelligence", "admin"],
    level: "advanced",
    outputType: "score",
    family: "segments",
    surfaces: ['admin_registry'],
    status: "pending_instrumentation",
    staticOrTrend: "hybrid",
    visibleByDefault: false,
    requiresGuardrail: true,
    minSample: 50,
    minNEff: 30,
    maxFreshnessHours: 24,
    requiresAnonymityGuardrail: true,
    exportable: true,
    uiVariant: "table_column",
    defaultSlot: "details",
    defaultSortOrder: 0,
    isWiredToReadModel: false,
    isWiredToUI: false,
  },
  segment_nps_gap: {
    id: "segment_nps_gap",
    name: "Segment Nps Gap",
    shortDescription: "Métrica: Segment Nps Gap",
    origin: "depth",
    allowedAudience: ["intelligence", "admin"],
    level: "advanced",
    outputType: "interval",
    family: "segments",
    surfaces: ['admin_registry'],
    status: "pending_instrumentation",
    staticOrTrend: "hybrid",
    visibleByDefault: false,
    requiresGuardrail: true,
    minSample: 50,
    minNEff: 30,
    maxFreshnessHours: 24,
    requiresAnonymityGuardrail: true,
    exportable: true,
    uiVariant: "table_column",
    defaultSlot: "details",
    defaultSortOrder: 0,
    isWiredToReadModel: false,
    isWiredToUI: false,
  },
  segment_attribute_gap: {
    id: "segment_attribute_gap",
    name: "Segment Attribute Gap",
    shortDescription: "Métrica: Segment Attribute Gap",
    origin: "depth",
    allowedAudience: ["intelligence", "admin"],
    level: "advanced",
    outputType: "interval",
    family: "depth",
    surfaces: ['admin_registry'],
    status: "pending_instrumentation",
    staticOrTrend: "hybrid",
    visibleByDefault: false,
    requiresGuardrail: true,
    minSample: 50,
    minNEff: 30,
    maxFreshnessHours: 24,
    requiresAnonymityGuardrail: true,
    exportable: true,
    uiVariant: "table_column",
    defaultSlot: "details",
    defaultSortOrder: 0,
    isWiredToReadModel: false,
    isWiredToUI: false,
  },
  signals_per_user: {
    id: "signals_per_user",
    name: "Signals Per User",
    shortDescription: "Métrica: Signals Per User",
    origin: "system",
    allowedAudience: ["intelligence", "admin"],
    level: "advanced",
    outputType: "number",
    family: "behavior",
    surfaces: ['admin_registry'],
    status: "pending_instrumentation",
    staticOrTrend: "hybrid",
    visibleByDefault: false,
    requiresGuardrail: true,
    minSample: 50,
    minNEff: 30,
    maxFreshnessHours: 24,
    requiresAnonymityGuardrail: true,
    exportable: true,
    uiVariant: "table_column",
    defaultSlot: "details",
    defaultSortOrder: 0,
    isWiredToReadModel: false,
    isWiredToUI: false,
  },
  signals_per_session: {
    id: "signals_per_session",
    name: "Signals Per Session",
    shortDescription: "Métrica: Signals Per Session",
    origin: "system",
    allowedAudience: ["intelligence", "admin"],
    level: "advanced",
    outputType: "number",
    family: "behavior",
    surfaces: ['admin_registry'],
    status: "pending_instrumentation",
    staticOrTrend: "hybrid",
    visibleByDefault: false,
    requiresGuardrail: true,
    minSample: 50,
    minNEff: 30,
    maxFreshnessHours: 24,
    requiresAnonymityGuardrail: true,
    exportable: true,
    uiVariant: "table_column",
    defaultSlot: "details",
    defaultSortOrder: 0,
    isWiredToReadModel: false,
    isWiredToUI: false,
  },
  module_share_of_activity: {
    id: "module_share_of_activity",
    name: "Module Share Of Activity",
    shortDescription: "Métrica: Module Share Of Activity",
    origin: "system",
    allowedAudience: ["intelligence", "admin"],
    level: "advanced",
    outputType: "interval",
    family: "rigor",
    surfaces: ['admin_registry'],
    status: "pending_instrumentation",
    staticOrTrend: "hybrid",
    visibleByDefault: false,
    requiresGuardrail: true,
    minSample: 50,
    minNEff: 30,
    maxFreshnessHours: 24,
    requiresAnonymityGuardrail: true,
    exportable: true,
    uiVariant: "kpi_card",
    defaultSlot: "details",
    defaultSortOrder: 0,
    isWiredToReadModel: false,
    isWiredToUI: false,
  },
  versus_to_depth_rate: {
    id: "versus_to_depth_rate",
    name: "Versus To Depth Rate",
    shortDescription: "Métrica: Versus To Depth Rate",
    origin: "depth",
    allowedAudience: ["intelligence", "admin"],
    level: "advanced",
    outputType: "interval",
    family: "depth",
    surfaces: ['admin_registry'],
    status: "pending_instrumentation",
    staticOrTrend: "hybrid",
    visibleByDefault: false,
    requiresGuardrail: true,
    minSample: 50,
    minNEff: 30,
    maxFreshnessHours: 24,
    requiresAnonymityGuardrail: true,
    exportable: true,
    uiVariant: "table_column",
    defaultSlot: "details",
    defaultSortOrder: 0,
    isWiredToReadModel: false,
    isWiredToUI: false,
  },
  actualidad_to_entity_explore_rate: {
    id: "actualidad_to_entity_explore_rate",
    name: "Actualidad To Entity Explore Rate",
    shortDescription: "Métrica: Actualidad To Entity Explore Rate",
    origin: "news",
    allowedAudience: ["intelligence", "admin"],
    level: "advanced",
    outputType: "entity_ref",
    family: "behavior",
    surfaces: ['admin_registry'],
    status: "pending_instrumentation",
    staticOrTrend: "hybrid",
    visibleByDefault: false,
    requiresGuardrail: true,
    minSample: 50,
    minNEff: 30,
    maxFreshnessHours: 24,
    requiresAnonymityGuardrail: true,
    exportable: true,
    uiVariant: "table_column",
    defaultSlot: "details",
    defaultSortOrder: 0,
    isWiredToReadModel: false,
    isWiredToUI: false,
  },
  session_depth: {
    id: "session_depth",
    name: "Session Depth",
    shortDescription: "Métrica: Session Depth",
    origin: "depth",
    allowedAudience: ["intelligence", "admin"],
    level: "advanced",
    outputType: "number",
    family: "depth",
    surfaces: ['admin_registry'],
    status: "pending_instrumentation",
    staticOrTrend: "hybrid",
    visibleByDefault: false,
    requiresGuardrail: true,
    minSample: 50,
    minNEff: 30,
    maxFreshnessHours: 24,
    requiresAnonymityGuardrail: true,
    exportable: true,
    uiVariant: "table_column",
    defaultSlot: "details",
    defaultSortOrder: 0,
    isWiredToReadModel: false,
    isWiredToUI: false,
  },
  avg_response_ms: {
    id: "avg_response_ms",
    name: "Avg Response Ms",
    shortDescription: "Métrica: Avg Response Ms",
    origin: "system",
    allowedAudience: ["intelligence", "admin"],
    level: "advanced",
    outputType: "number",
    family: "rigor",
    surfaces: ['admin_registry'],
    status: "pending_instrumentation",
    staticOrTrend: "hybrid",
    visibleByDefault: false,
    requiresGuardrail: true,
    minSample: 50,
    minNEff: 30,
    maxFreshnessHours: 24,
    requiresAnonymityGuardrail: true,
    exportable: true,
    uiVariant: "table_column",
    defaultSlot: "details",
    defaultSortOrder: 0,
    isWiredToReadModel: false,
    isWiredToUI: false,
  },
  completion_rate: {
    id: "completion_rate",
    name: "Completion Rate",
    shortDescription: "Métrica: Completion Rate",
    origin: "system",
    allowedAudience: ["intelligence", "admin"],
    level: "advanced",
    outputType: "interval",
    family: "behavior",
    surfaces: ['admin_registry'],
    status: "pending_instrumentation",
    staticOrTrend: "hybrid",
    visibleByDefault: false,
    requiresGuardrail: true,
    minSample: 50,
    minNEff: 30,
    maxFreshnessHours: 24,
    requiresAnonymityGuardrail: true,
    exportable: true,
    uiVariant: "table_column",
    defaultSlot: "details",
    defaultSortOrder: 0,
    isWiredToReadModel: false,
    isWiredToUI: false,
  },
  abandonment_rate: {
    id: "abandonment_rate",
    name: "Abandonment Rate",
    shortDescription: "Métrica: Abandonment Rate",
    origin: "system",
    allowedAudience: ["intelligence", "admin"],
    level: "advanced",
    outputType: "interval",
    family: "behavior",
    surfaces: ['admin_registry'],
    status: "pending_instrumentation",
    staticOrTrend: "hybrid",
    visibleByDefault: false,
    requiresGuardrail: true,
    minSample: 50,
    minNEff: 30,
    maxFreshnessHours: 24,
    requiresAnonymityGuardrail: true,
    exportable: true,
    uiVariant: "table_column",
    defaultSlot: "details",
    defaultSortOrder: 0,
    isWiredToReadModel: false,
    isWiredToUI: false,
  },
  skip_rate: {
    id: "skip_rate",
    name: "Skip Rate",
    shortDescription: "Métrica: Skip Rate",
    origin: "system",
    allowedAudience: ["intelligence", "admin"],
    level: "advanced",
    outputType: "interval",
    family: "behavior",
    surfaces: ['admin_registry'],
    status: "pending_instrumentation",
    staticOrTrend: "hybrid",
    visibleByDefault: false,
    requiresGuardrail: true,
    minSample: 50,
    minNEff: 30,
    maxFreshnessHours: 24,
    requiresAnonymityGuardrail: true,
    exportable: true,
    uiVariant: "table_column",
    defaultSlot: "details",
    defaultSortOrder: 0,
    isWiredToReadModel: false,
    isWiredToUI: false,
  },
  flow_path_share: {
    id: "flow_path_share",
    name: "Flow Path Share",
    shortDescription: "Métrica: Flow Path Share",
    origin: "system",
    allowedAudience: ["intelligence", "admin"],
    level: "advanced",
    outputType: "interval",
    family: "rigor",
    surfaces: ['admin_registry'],
    status: "pending_instrumentation",
    staticOrTrend: "hybrid",
    visibleByDefault: false,
    requiresGuardrail: true,
    minSample: 50,
    minNEff: 30,
    maxFreshnessHours: 24,
    requiresAnonymityGuardrail: true,
    exportable: true,
    uiVariant: "kpi_card",
    defaultSlot: "details",
    defaultSortOrder: 0,
    isWiredToReadModel: false,
    isWiredToUI: false,
  },
  returning_user_rate: {
    id: "returning_user_rate",
    name: "Returning User Rate",
    shortDescription: "Métrica: Returning User Rate",
    origin: "system",
    allowedAudience: ["intelligence", "admin"],
    level: "advanced",
    outputType: "interval",
    family: "behavior",
    surfaces: ['admin_registry'],
    status: "pending_instrumentation",
    staticOrTrend: "hybrid",
    visibleByDefault: false,
    requiresGuardrail: true,
    minSample: 50,
    minNEff: 30,
    maxFreshnessHours: 24,
    requiresAnonymityGuardrail: true,
    exportable: true,
    uiVariant: "table_column",
    defaultSlot: "details",
    defaultSortOrder: 0,
    isWiredToReadModel: false,
    isWiredToUI: false,
  },
  verified_weight_share: {
    id: "verified_weight_share",
    name: "Verified Weight Share",
    shortDescription: "Métrica: Verified Weight Share",
    origin: "system",
    allowedAudience: ["intelligence", "admin"],
    level: "advanced",
    outputType: "interval",
    family: "rigor",
    surfaces: ['admin_registry'],
    status: "pending_instrumentation",
    staticOrTrend: "hybrid",
    visibleByDefault: false,
    requiresGuardrail: true,
    minSample: 50,
    minNEff: 30,
    maxFreshnessHours: 24,
    requiresAnonymityGuardrail: true,
    exportable: true,
    uiVariant: "kpi_card",
    defaultSlot: "details",
    defaultSortOrder: 0,
    isWiredToReadModel: false,
    isWiredToUI: false,
  },
  suspicious_weight_ratio: {
    id: "suspicious_weight_ratio",
    name: "Suspicious Weight Ratio",
    shortDescription: "Métrica: Suspicious Weight Ratio",
    origin: "system",
    allowedAudience: ["intelligence", "admin"],
    level: "advanced",
    outputType: "number",
    family: "rigor",
    surfaces: ['admin_registry'],
    status: "pending_instrumentation",
    staticOrTrend: "hybrid",
    visibleByDefault: false,
    requiresGuardrail: true,
    minSample: 50,
    minNEff: 30,
    maxFreshnessHours: 24,
    requiresAnonymityGuardrail: true,
    exportable: true,
    uiVariant: "table_column",
    defaultSlot: "details",
    defaultSortOrder: 0,
    isWiredToReadModel: false,
    isWiredToUI: false,
  },
  anomaly_risk_score: {
    id: "anomaly_risk_score",
    name: "Anomaly Risk Score",
    shortDescription: "Métrica: Anomaly Risk Score",
    origin: "system",
    allowedAudience: ["intelligence", "admin"],
    level: "advanced",
    outputType: "score",
    family: "depth",
    surfaces: ['admin_registry'],
    status: "pending_instrumentation",
    staticOrTrend: "hybrid",
    visibleByDefault: false,
    requiresGuardrail: true,
    minSample: 50,
    minNEff: 30,
    maxFreshnessHours: 24,
    requiresAnonymityGuardrail: true,
    exportable: true,
    uiVariant: "kpi_card",
    defaultSlot: "details",
    defaultSortOrder: 0,
    isWiredToReadModel: false,
    isWiredToUI: false,
  },
  integrity_score: {
    id: "integrity_score",
    name: "Integrity Score",
    shortDescription: "Integridad agregada de las señales (frescura + n_eff + consistencia temporal).",
    origin: "system",
    allowedAudience: ["intelligence", "admin", "results"],
    level: "advanced",
    outputType: "score",
    family: "depth",
    surfaces: ['b2b_overview_top','admin_registry','results_hero'],
    status: "live",
    staticOrTrend: "hybrid",
    visibleByDefault: true,
    requiresGuardrail: true,
    minSample: 50,
    minNEff: 30,
    maxFreshnessHours: 24,
    requiresAnonymityGuardrail: true,
    exportable: true,
    uiVariant: "kpi_card",
    defaultSlot: "hero",
    defaultSortOrder: 0,
    isWiredToReadModel: true,
    isWiredToUI: true,
  },
  fraud_flag_count: {
    id: "fraud_flag_count",
    name: "Fraud Flag Count",
    shortDescription: "Métrica: Fraud Flag Count",
    origin: "system",
    allowedAudience: ["intelligence", "admin"],
    level: "advanced",
    outputType: "number",
    family: "integrity",
    surfaces: ['admin_registry'],
    status: "pending_instrumentation",
    staticOrTrend: "hybrid",
    visibleByDefault: false,
    requiresGuardrail: true,
    minSample: 50,
    minNEff: 30,
    maxFreshnessHours: 24,
    requiresAnonymityGuardrail: true,
    exportable: true,
    uiVariant: "table_column",
    defaultSlot: "details",
    defaultSortOrder: 0,
    isWiredToReadModel: false,
    isWiredToUI: false,
  },
  data_cleanliness_label: {
    id: "data_cleanliness_label",
    name: "Data Cleanliness Label",
    shortDescription: "Métrica: Data Cleanliness Label",
    origin: "system",
    allowedAudience: ["intelligence", "admin"],
    level: "advanced",
    outputType: "label",
    family: "integrity",
    surfaces: ['admin_registry'],
    status: "pending_instrumentation",
    staticOrTrend: "hybrid",
    visibleByDefault: false,
    requiresGuardrail: true,
    minSample: 50,
    minNEff: 30,
    maxFreshnessHours: 24,
    requiresAnonymityGuardrail: true,
    exportable: true,
    uiVariant: "editorial_chip",
    defaultSlot: "details",
    defaultSortOrder: 0,
    isWiredToReadModel: false,
    isWiredToUI: false,
  },
  premium_export_ready: {
    id: "premium_export_ready",
    name: "Premium Export Ready",
    shortDescription: "Métrica: Premium Export Ready",
    origin: "system",
    allowedAudience: ["intelligence", "admin"],
    level: "advanced",
    outputType: "number",
    family: "rigor",
    surfaces: ['admin_registry'],
    status: "pending_instrumentation",
    staticOrTrend: "hybrid",
    visibleByDefault: false,
    requiresGuardrail: true,
    minSample: 50,
    minNEff: 30,
    maxFreshnessHours: 24,
    requiresAnonymityGuardrail: true,
    exportable: true,
    uiVariant: "table_column",
    defaultSlot: "details",
    defaultSortOrder: 0,
    isWiredToReadModel: false,
    isWiredToUI: false,
  },
  opinascore_v1: {
    id: "opinascore_v1",
    name: "Opinascore V1",
    shortDescription: "Score integrador (0-100) que combina opinascore_value × integrity_score × n_eff. Hero del drawer B2B.",
    origin: "system",
    allowedAudience: ["intelligence", "admin"],
    level: "advanced",
    outputType: "score",
    family: "depth",
    surfaces: ['admin_registry', 'b2b_deep_dive_body'],
    status: "live",
    staticOrTrend: "hybrid",
    visibleByDefault: true,
    requiresGuardrail: true,
    minSample: 50,
    minNEff: 30,
    maxFreshnessHours: 24,
    requiresAnonymityGuardrail: true,
    exportable: true,
    uiVariant: "kpi_card",
    defaultSlot: "hero",
    defaultSortOrder: 0,
    isWiredToReadModel: true,
    isWiredToUI: true,
  },
  preference_vs_quality_gap: {
    id: "preference_vs_quality_gap",
    name: "Preference Vs Quality Gap",
    shortDescription: "Métrica: Preference Vs Quality Gap",
    origin: "versus",
    allowedAudience: ["intelligence", "admin"],
    level: "advanced",
    outputType: "interval",
    family: "market",
    surfaces: ['admin_registry'],
    status: "pending_instrumentation",
    staticOrTrend: "hybrid",
    visibleByDefault: false,
    requiresGuardrail: true,
    minSample: 50,
    minNEff: 30,
    maxFreshnessHours: 24,
    requiresAnonymityGuardrail: true,
    exportable: true,
    uiVariant: "table_column",
    defaultSlot: "details",
    defaultSortOrder: 0,
    isWiredToReadModel: false,
    isWiredToUI: false,
  },
  preference_shift_after_news: {
    id: "preference_shift_after_news",
    name: "Preference Shift After News",
    shortDescription: "Métrica: Preference Shift After News",
    origin: "news",
    allowedAudience: ["intelligence", "admin"],
    level: "advanced",
    outputType: "number",
    family: "market",
    surfaces: ['admin_registry'],
    status: "pending_instrumentation",
    staticOrTrend: "hybrid",
    visibleByDefault: false,
    requiresGuardrail: true,
    minSample: 50,
    minNEff: 30,
    maxFreshnessHours: 24,
    requiresAnonymityGuardrail: true,
    exportable: true,
    uiVariant: "table_column",
    defaultSlot: "details",
    defaultSortOrder: 0,
    isWiredToReadModel: false,
    isWiredToUI: false,
  },
  attribute_shift_after_news: {
    id: "attribute_shift_after_news",
    name: "Attribute Shift After News",
    shortDescription: "Métrica: Attribute Shift After News",
    origin: "news",
    allowedAudience: ["intelligence", "admin"],
    level: "advanced",
    outputType: "number",
    family: "depth",
    surfaces: ['admin_registry'],
    status: "pending_instrumentation",
    staticOrTrend: "hybrid",
    visibleByDefault: false,
    requiresGuardrail: true,
    minSample: 50,
    minNEff: 30,
    maxFreshnessHours: 24,
    requiresAnonymityGuardrail: true,
    exportable: true,
    uiVariant: "table_column",
    defaultSlot: "details",
    defaultSortOrder: 0,
    isWiredToReadModel: false,
    isWiredToUI: false,
  },
  segment_shift_after_news: {
    id: "segment_shift_after_news",
    name: "Segment Shift After News",
    shortDescription: "Métrica: Segment Shift After News",
    origin: "news",
    allowedAudience: ["intelligence", "admin"],
    level: "advanced",
    outputType: "number",
    family: "actualidad",
    surfaces: ['admin_registry'],
    status: "pending_instrumentation",
    staticOrTrend: "hybrid",
    visibleByDefault: false,
    requiresGuardrail: true,
    minSample: 50,
    minNEff: 30,
    maxFreshnessHours: 24,
    requiresAnonymityGuardrail: true,
    exportable: true,
    uiVariant: "table_column",
    defaultSlot: "details",
    defaultSortOrder: 0,
    isWiredToReadModel: false,
    isWiredToUI: false,
  },
  tournament_vs_versus_consistency: {
    id: "tournament_vs_versus_consistency",
    name: "Tournament Vs Versus Consistency",
    shortDescription: "¿El campeón del torneo coincide con el líder de versus? Label cross-módulo.",
    origin: "versus",
    allowedAudience: ["intelligence", "admin", "results"],
    level: "advanced",
    outputType: "label",
    family: "rigor",
    surfaces: ['admin_registry', 'results_hero'],
    status: "live",
    staticOrTrend: "static",
    visibleByDefault: true,
    requiresGuardrail: true,
    minSample: 50,
    minNEff: 30,
    maxFreshnessHours: 24,
    requiresAnonymityGuardrail: true,
    exportable: true,
    uiVariant: "editorial_chip",
    defaultSlot: "details",
    defaultSortOrder: 0,
    isWiredToReadModel: true,
    isWiredToUI: true,
  },
  cross_module_coherence_score: {
    id: "cross_module_coherence_score",
    name: "Cross Module Coherence Score",
    shortDescription: "Coherencia entre módulos (versus vs torneo). Derivado del match de líderes.",
    origin: "system",
    allowedAudience: ["intelligence", "admin", "results"],
    level: "advanced",
    outputType: "score",
    family: "depth",
    surfaces: ['admin_registry', 'results_hero'],
    status: "live",
    staticOrTrend: "static",
    visibleByDefault: true,
    requiresGuardrail: true,
    minSample: 50,
    minNEff: 30,
    maxFreshnessHours: 24,
    requiresAnonymityGuardrail: true,
    exportable: true,
    uiVariant: "kpi_card",
    defaultSlot: "details",
    defaultSortOrder: 0,
    isWiredToReadModel: true,
    isWiredToUI: true,
  },
  entity_volatility_across_modules: {
    id: "entity_volatility_across_modules",
    name: "Entity Volatility Across Modules",
    shortDescription: "Métrica: Entity Volatility Across Modules",
    origin: "system",
    allowedAudience: ["intelligence", "admin"],
    level: "advanced",
    outputType: "entity_ref",
    family: "rigor",
    surfaces: ['admin_registry'],
    status: "pending_instrumentation",
    staticOrTrend: "hybrid",
    visibleByDefault: false,
    requiresGuardrail: true,
    minSample: 50,
    minNEff: 30,
    maxFreshnessHours: 24,
    requiresAnonymityGuardrail: true,
    exportable: true,
    uiVariant: "table_column",
    defaultSlot: "details",
    defaultSortOrder: 0,
    isWiredToReadModel: false,
    isWiredToUI: false,
  },
  trust_vs_choice_gap: {
    id: "trust_vs_choice_gap",
    name: "Trust Vs Choice Gap",
    shortDescription: "Métrica: Trust Vs Choice Gap",
    origin: "system",
    allowedAudience: ["intelligence", "admin"],
    level: "advanced",
    outputType: "interval",
    family: "segments",
    surfaces: ['admin_registry'],
    status: "pending_instrumentation",
    staticOrTrend: "hybrid",
    visibleByDefault: false,
    requiresGuardrail: true,
    minSample: 50,
    minNEff: 30,
    maxFreshnessHours: 24,
    requiresAnonymityGuardrail: true,
    exportable: true,
    uiVariant: "table_column",
    defaultSlot: "details",
    defaultSortOrder: 0,
    isWiredToReadModel: false,
    isWiredToUI: false,
  },
};
