import { createClient } from '@supabase/supabase-js';
import * as dotenv from 'dotenv';
import { resolve } from 'path';

// Load environment variables from .env.local
dotenv.config({ path: resolve(process.cwd(), '.env.development.local') });

const supabaseUrl = process.env.VITE_SUPABASE_URL || '';
const supabaseKey = process.env.SUPABASE_SERVICE_ROLE_KEY || process.env.VITE_SUPABASE_ANON_KEY || '';

if (!supabaseUrl || !supabaseKey) {
  console.error("Faltan las variables de entorno de Supabase.");
  process.exit(1);
}

const supabase = createClient(supabaseUrl, supabaseKey);

function generateSlug(title: string) {
    return title.toLowerCase().replace(/[^a-z0-9]+/g, '_').replace(/(^_|_$)/g, '') + '_' + Math.random().toString(36).substring(2, 7);
}

function slugify(text: string) {
    return text.toString().toLowerCase()
        .normalize('NFD')
        .replace(/[̀-ͯ]/g, '')
        .replace(/\s+/g, '-')
        .replace(/[^\w\-]+/g, '')
        .replace(/\-\-+/g, '-')
        .replace(/^-+/, '')
        .replace(/-+$/, '');
}

async function ensureCategoryExists(subcategoryName: string) {
    const slug = slugify(subcategoryName);
    
    // Check if it exists
    const { data } = await supabase.from('categories').select('id, slug').eq('slug', slug).single();
    if (data) return data;

    // Create it
    const { data: newCat, error } = await supabase.from('categories').insert({
        name: subcategoryName,
        slug: slug,
        emoji: '✨',
        active: true,
        generation_mode: 'ai_curated_pairs'
    }).select('id, slug').single();

    if (error) {
        console.error("Error creating category:", slug, error);
        throw error;
    }
    return newCat;
}

async function nukeOldBattles() {
    console.log("Nukeando batallas antiguas generadas por IA...");
    // We only delete battles that were auto-generated or all active?
    // According to the plan, we delete all autogenerated battles to start fresh.
    // The previous script created battles but they might have had 'active' status.
    // Let's delete all battles since we are starting fresh with V3 catalog.
    const { error } = await supabase.from('battles').delete().neq('id', '00000000-0000-0000-0000-000000000000'); // match all
    if (error) {
        console.error("Error al borrar batallas:", error.message);
    } else {
        console.log("Todas las batallas antiguas borradas.");
    }
}

async function generateAllVersus() {
  console.log("=========================================");
  console.log("INICIANDO GENERACIÓN MASIVA DE VERSUS LOCAL (V3)");
  console.log("=========================================\n");

  try {
    await nukeOldBattles();

    // 1. Obtener TODAS las marcas de V3
    const { data: entities, error: entError } = await supabase
        .from('entities')
        .select('*')
        .eq('type', 'brand')
        .not('metadata->subcategory', 'is', null);

    if (entError) throw entError;

    if (!entities || entities.length === 0) {
        console.log("No se encontraron entidades V3.");
        return;
    }

    // 2. Agrupar por subcategoria
    const groupedBySubcategory: Record<string, any[]> = {};
    entities.forEach(ent => {
        const subcat = ent.metadata?.subcategory;
        if (subcat) {
            if (!groupedBySubcategory[subcat]) groupedBySubcategory[subcat] = [];
            groupedBySubcategory[subcat].push(ent);
        }
    });

    let totalCreated = 0;

    for (const [subcategoryName, brands] of Object.entries(groupedBySubcategory)) {
        if (brands.length < 2) {
            console.log(`Omitiendo ${subcategoryName}: solo ${brands.length} marcas.`);
            continue;
        }

        console.log(`\nProcesando subcategoría: ${subcategoryName} (${brands.length} marcas)`);
        const categoryDoc = await ensureCategoryExists(subcategoryName);

        // 3. Generar combinaciones N*(N-1)/2
        let createdInProgress = 0;
        for (let i = 0; i < brands.length; i++) {
            for (let j = i + 1; j < brands.length; j++) {
                const brandA = brands[i];
                const brandB = brands[j];

                if (brandA.name.toLowerCase().trim() === brandB.name.toLowerCase().trim()) continue;

                // Crear Batalla
                const finalTitle = `Batalla: ${brandA.name} vs ${brandB.name}`;
                const finalDescription = `¿Cuál prefieres entre ${brandA.name} y ${brandB.name}?`;
                const slug = generateSlug(finalTitle);

                const { data: newBattle, error: battleError } = await supabase
                    .from('battles')
                    .insert({
                        slug: slug,
                        title: finalTitle,
                        description: finalDescription,
                        category_id: categoryDoc.id,
                        status: 'active'
                    })
                    .select('*')
                    .single();

                if (battleError || !newBattle) {
                    console.error(`  [X] Error creando batalla ${finalTitle}:`, battleError);
                    continue;
                }

                // Crear opciones
                const { error: optionsError } = await supabase
                    .from('battle_options')
                    .insert([
                        {
                            battle_id: newBattle.id,
                            label: brandA.name,
                            brand_id: brandA.id,
                            image_url: brandA.image_url,
                            sort_order: 1
                        },
                        {
                            battle_id: newBattle.id,
                            label: brandB.name,
                            brand_id: brandB.id,
                            image_url: brandB.image_url,
                            sort_order: 2
                        }
                    ]);

                if (optionsError) {
                    console.error(`  [X] Error creando opciones para ${finalTitle}:`, optionsError);
                    continue;
                }

                // Crear instancia
                const { error: instanceError } = await supabase
                    .from('battle_instances')
                    .insert({
                        battle_id: newBattle.id,
                        version: 1,
                        starts_at: new Date().toISOString()
                    });
                
                if (instanceError) {
                    console.error(`  [X] Error creando instancia para ${finalTitle}:`, instanceError);
                    continue;
                }

                console.log(`  [+] Creada: ${brandA.name} vs ${brandB.name}`);
                createdInProgress++;
                totalCreated++;
                
                await new Promise(resolve => setTimeout(resolve, 20));
            }
        }
        console.log(`  -> Se crearon ${createdInProgress} batallas en ${subcategoryName}.`);
    }

    console.log("\n=========================================");
    console.log(`🎉 GENERACIÓN MASIVA FINALIZADA. TOTAL CREADAS: ${totalCreated}`);
    console.log("=========================================\n");

  } catch (error) {
    console.error("Error al generar versus:", error);
  }
}

generateAllVersus();
