-- Migración: Agregar columna de secuencia cronológica absoluta para desempate
-- Fecha: 30 Mar 2026

-- 1. Añadimos la columna vacía
ALTER TABLE public.results_publication_state 
ADD COLUMN IF NOT EXISTS publication_seq BIGINT;

-- 2. Backfill HISTÓRICO DETERMINISTA: Aseguramos que la secuencia antigua se asigne
-- estrictamente de acuerdo con el timestamp `published_at`, desde el más viejo (1) al más nuevo.
-- Este paso evita que PostgreSQL asigne IDs basados en el orden físico aleatorio del Heap.
WITH RankedHistory AS (
  SELECT id, row_number() OVER (ORDER BY published_at ASC) as assigned_seq
  FROM public.results_publication_state
  WHERE publication_seq IS NULL
)
UPDATE public.results_publication_state rps
SET publication_seq = rh.assigned_seq
FROM RankedHistory rh
WHERE rps.id = rh.id;

-- 2.5 Aseguramos NOT NULL antes de convertir a IDENTITY
ALTER TABLE public.results_publication_state ALTER COLUMN publication_seq SET NOT NULL;

-- 3. Ahora que el backfill está completo, atamos la columna al secuenciador automático
-- de Postgres, partiendo del número más alto existente o de 1.
DO $$
DECLARE
  max_val BIGINT;
BEGIN
  SELECT COALESCE(MAX(publication_seq), 0) INTO max_val FROM public.results_publication_state;
  
  EXECUTE 'ALTER TABLE public.results_publication_state 
           ALTER COLUMN publication_seq ADD GENERATED BY DEFAULT AS IDENTITY (RESTART WITH ' || (max_val + 1) || ')';
END $$;

-- 4. Limpiar el índice de un solo campo del parche anterior
DROP INDEX IF EXISTS idx_results_publication_state_published_desc;

-- 5. Crear el índice compuesto definitivo para la query de último snapshot
CREATE INDEX IF NOT EXISTS idx_results_publication_state_latest 
ON public.results_publication_state (published_at DESC, publication_seq DESC);
